---
- name: Install postgresql
  ansible.builtin.apt:
    name: 'postgresql-{{ (postgresql_version|split("."))[0] }}={{ postgresql_version }}*'
    state: present
  become: true

- name: Notify restart postgresql if not started
  ansible.builtin.command: systemctl status postgresql
  become: true
  register: postgresql_service_status
  changed_when: postgresql_service_status.rc != 0
  failed_when: false
  notify:
    - Restart postgresql
