---
- name: Restart node exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart node-exporter

- name: Check systemd service
  ansible.builtin.command: systemctl status prometheus-node-exporter
  become: true
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ node_exporter_listen_port }}'
    state: started
  listen: Check
