---
- name: Restart node exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart node-exporter
