---
- name: Install logstash
  ansible.builtin.apt:
    name: 'logstash=1:{{ logstash_version }}*'
    state: present
  become: true

- name: Notify restart logstash if not started
  ansible.builtin.command: systemctl status logstash
  become: true
  register: logstash_service_status
  changed_when: logstash_service_status.rc != 0
  failed_when: false
  notify:
    - Restart logstash
