---
- name: Check internal IP
  ansible.builtin.command:
    cmd: |
      ip address show dev {{ network_internal_iface }}
  register: network_check_internal_ip_stats
  changed_when: false
  failed_when: |
    network_check_internal_ip_stats.rc != 0 or not network_check_internal_ip_stats.stdout is search(network_internal_address)
  listen: Check
