---
- name: Install nginx
  ansible.builtin.apt:
    name: 'nginx={{ nginx_version }}*'
    state: present
  become: true

- name: Copy mime types
  ansible.builtin.copy:
    src: etc/nginx/mime.types
    dest: /etc/nginx/mime.types
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Copy dhparam
  ansible.builtin.copy:
    src: etc/nginx/dhparam
    dest: /etc/nginx/dhparam
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Copy gzip config
  ansible.builtin.template:
    src: etc/nginx/conf.d/gzip.conf
    dest: /etc/nginx/conf.d/gzip.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Copy log format config
  ansible.builtin.template:
    src: etc/nginx/conf.d/log_format.conf
    dest: /etc/nginx/conf.d/log_format.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Copy ssl config
  ansible.builtin.template:
    src: etc/nginx/conf.d/ssl.conf
    dest: /etc/nginx/conf.d/ssl.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Install stub status site
  ansible.builtin.template:
    src: etc/nginx/sites-available/stub_status.conf
    dest: /etc/nginx/sites-available/stub_status.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Enable stub status site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/stub_status.conf
    dest: /etc/nginx/sites-enabled/stub_status.conf
    owner: root
    group: root
    state: link
  become: true
  notify:
    - Reload nginx

- name: Copy nginx config
  ansible.builtin.template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: nginx -t -c %s
  become: true
  notify:
    - Reload nginx

- name: Remove default server
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify:
    - Reload nginx

- name: Notify restart nginx if not started
  ansible.builtin.command: systemctl status nginx
  become: true
  register: nginx_service_status
  changed_when: nginx_service_status.rc != 0
  failed_when: false
  notify:
    - Restart nginx
