---
- name: Install redis-server
  ansible.builtin.apt:
    name: 'redis-server=5:{{ redis_server_version }}*'
    state: present
  become: true

- name: Copy redis config
  ansible.builtin.template:
    src: etc/redis/redis.conf
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: '0640'
    backup: true
  become: true
  notify:
    - Restart redis-server

- name: Notify restart redis-server if not started
  ansible.builtin.command: systemctl status redis-server
  become: true
  register: redis_server_service_status
  changed_when: redis_server_service_status.rc != 0
  failed_when: false
  notify:
    - Restart redis-server
