---
- name: Install redis-server
  ansible.builtin.apt:
    name: 'redis-server=5:{{ redis_server_version }}*'
    state: present
  become: true

- name: Notify restart redis-server if not started
  ansible.builtin.command: systemctl status redis-server
  become: true
  register: redis_server_service_status
  changed_when: redis_server_service_status.rc != 0
  failed_when: false
  notify:
    - Restart redis-server
