---
- name: Install input config of nginx access.log
  ansible.builtin.template:
    src: etc/fluent-bit/input-conf.d/nginx_ltsv_access_log_xxx.conf
    dest: '/etc/fluent-bit/input-conf.d/nginx_ltsv_access_log_{{ item }}.conf'
    owner: root
    group: root
    mode: '0640'
    backup: true
    validate: /opt/bin/fluent-bit-validate %s
  become: true
  loop: '{{ fluent_bit_input_nginx_log_access_entries|dict2items|map(attribute="key") }}'
  notify:
    - Restart fluent-bit

- name: Install input config of nginx error.log
  ansible.builtin.template:
    src: etc/fluent-bit/input-conf.d/nginx_error_log.conf
    dest: /etc/fluent-bit/input-conf.d/nginx_error_log.conf
    owner: root
    group: root
    mode: '0640'
    backup: true
    validate: /opt/bin/fluent-bit-validate %s
  become: true
  notify:
    - Restart fluent-bit
