---
- name: Reload blackbox exporter
  ansible.builtin.set_fact:
    blackbox_exporter_handler_state: reloaded
  become: true
  listen: Reload blackbox-exporter

- name: Restart blackbox exporter
  ansible.builtin.set_fact:
    blackbox_exporter_handler_state: restarted
  become: true
  listen: Restart blackbox-exporter

- name: Restart or reload blackbox exporter
  ansible.builtin.systemd:
    name: prometheus-blackbox-exporter
    state: '{{ blackbox_exporter_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart blackbox-exporter
  - Reload blackbox-exporter

- name: Check systemd service
  ansible.builtin.command: systemctl status prometheus-blackbox-exporter
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ blackbox_exporter_listen_port }}'
    state: started
    timeout: 60
  listen: Check
