global:
  scrape_interval: 15s
  evaluation_interval: 1m
  scrape_timeout: 10s

rule_files: []

scrape_configs:
{% for scrape_config in prometheus_scrape_configs %}
- job_name: {{ scrape_config.job_name|to_yaml }}
{% if 'scrape_interval' in scrape_config %}
  scrape_interval: {{ scrape_config.scrape_interval }}
{% endif %}
{% if 'scrape_timeout' in scrape_config %}
  scrape_timeout: {{ scrape_config.scrape_timeout }}
{% endif %}
  metrics_path: {{ scrape_config.metrics_path|to_yaml }}
  scheme: {{ scrape_config.scheme|to_yaml }}
  params:
{{ scrape_config.params|to_yaml(indent=4) }}
  tls_config:
{% if scrape_config.enable_tls_client_verification %}
    cert_file: /etc/prometheus/tls_config/client_certificate.pem
    key_file: /etc/prometheus/tls_config/client_privkey.pem
{% endif %}
  static_configs:
{{ scrape_config.static_configs|to_yaml(indent=4) }}
  relabel_configs:
{{ scrape_config.relabel_configs|to_yaml(indent=4) }}
{% endfor %}
