---
- name: Install mastodon site
  ansible.builtin.template:
    src: etc/nginx/sites-available/mastodon_front.conf
    dest: /etc/nginx/sites-available/mastodon_front.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nginx

- name: Enable http redirector site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mastodon_front.conf
    dest: /etc/nginx/sites-enabled/mastodon_front.conf
    owner: root
    group: root
    state: link
  become: true
  notify:
    - Restart nginx
