package nginx_site_private_ca

import "mizunashi.work/pkg/roles/openssl_ocsp_responder"

openssl_ocsp_responder

nginx_site_private_ca_listen_port: uint
nginx_site_private_ca_domain: string

nginx_site_private_ca_root_certificate: string
nginx_site_private_ca_root_crl: string

nginx_site_private_ca_inter_tls_certificate: string
nginx_site_private_ca_inter_tls_crl: string
