---
- name: Copy grafana gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/grafana.gpg
    dest: /usr/share/keyrings/grafana.gpg
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install grafana repository
  ansible.builtin.template:
    src: etc/apt/sources.list.d/grafana.list
    dest: /etc/apt/sources.list.d/grafana.list
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  register: grafana_install_repository_result

- name: Install grafana
  ansible.builtin.apt:
    name: 'grafana={{ grafana_version }}*'
    state: present
    update_cache: '{{ grafana_install_repository_result.changed }}'
  become: true
  notify: Restart grafana

- name: Copy grafana config
  ansible.builtin.template:
    src: etc/grafana/grafana.ini
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: '0640'
    backup: true
  become: true
  notify:
    - Restart grafana

- name: Copy grafana private config
  ansible.builtin.template:
    src: etc/default/grafana-server.private
    dest: /etc/default/grafana-server.private
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  diff: false
  notify:
    - Restart grafana

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/grafana-server.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override service
  ansible.builtin.template:
    src: etc/systemd/system/grafana-server.service.d/override.conf
    dest: /etc/systemd/system/grafana-server.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart grafana

- name: Validate systemd service
  ansible.builtin.command: |
    /opt/bin/systemd-validate /lib/systemd/system/grafana-server.service
  become: true
  changed_when: false
  register: grafana_systemd_validate_result
  failed_when: |
    grafana_systemd_validate_result.rc != 0
    or grafana_systemd_validate_result.stderr != ''

- name: Notify restart grafana if not started
  ansible.builtin.command: systemctl status grafana-server
  become: true
  register: grafana_service_status
  changed_when: grafana_service_status.rc != 0
  failed_when: false
  notify:
    - Restart grafana
