---
- name: Reload caddy
  ansible.builtin.set_fact:
    caddy_handler_state: reloaded
  become: true
  listen: Reload caddy

- name: Restart caddy
  ansible.builtin.set_fact:
    caddy_handler_state: restarted
  become: true
  listen: Restart caddy

- name: Find caddy logs
  ansible.builtin.find:
    paths: /var/log/caddy
    file_type: file
    patterns: '*.log'
  become: true
  register: caddy_log_files
  listen:
  - Restart caddy
  - Reload caddy

- name: Make correct permissions of caddy logs
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: file
    owner: caddy
    group: adm
    mode: '0640'
  become: true
  loop: '{{ caddy_log_files.files }}'
  listen:
  - Restart caddy
  - Reload caddy

- name: Restart or reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: '{{ caddy_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart caddy
  - Reload caddy

- name: Check systemd service
  ansible.builtin.command: systemctl status caddy
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ caddy_metrics_listen_port }}'
    state: started
    timeout: 60
  listen: Check
