---
- name: Install apticron
  ansible.builtin.apt:
    name: 'apticron={{ apticron_version }}*'
    state: present
  become: true

- name: Copy apticron config
  ansible.builtin.template:
    src: usr/lib/apticron/apticron.conf
    dest: /usr/lib/apticron/apticron.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
