---
- name: Install elasticsearch exporter
  ansible.builtin.apt:
    name: 'prometheus-elasticsearch-exporter={{ elasticsearch_exporter_version }}*'
    state: present
  become: true

- name: Copy elasticsearch exporter environment
  ansible.builtin.template:
    src: etc/default/prometheus-elasticsearch-exporter
    dest: /etc/default/prometheus-elasticsearch-exporter
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart elasticsearch-exporter

- name: Copy elasticsearch exporter private environment
  ansible.builtin.template:
    src: etc/default/prometheus-elasticsearch-exporter.private
    dest: /etc/default/prometheus-elasticsearch-exporter.private
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  diff: false
  notify:
    - Restart elasticsearch-exporter

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus-elasticsearch-exporter.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override service
  ansible.builtin.template:
    src: etc/systemd/system/prometheus-elasticsearch-exporter.service.d/override.conf
    dest: /etc/systemd/system/prometheus-elasticsearch-exporter.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  notify:
    - Restart elasticsearch-exporter

- name: Validate systemd service
  ansible.builtin.command: |
    /opt/bin/systemd-validate /lib/systemd/system/prometheus-elasticsearch-exporter.service
  become: true
  changed_when: false
  register: elasticsearch_exporter_systemd_validate_result
  failed_when: |
    elasticsearch_exporter_systemd_validate_result.rc != 0
    or elasticsearch_exporter_systemd_validate_result.stderr != ''

- name: Notify restart elasticsearch exporter if not started
  ansible.builtin.command: systemctl status prometheus-elasticsearch-exporter
  become: true
  register: elasticsearch_exporter_service_status
  changed_when: elasticsearch_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart elasticsearch-exporter
