- hosts: all

  roles:
  - base
  - nftables
  - fail2ban
  - apticron
  - openssh_server
  - node_exporter
  - exim

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- import_playbook: ./playbook-internal.yml
- import_playbook: ./playbook-public.yml
