- hosts: all

  roles:
  - base
  - nftables
  - fail2ban
  - openssh_server
  - nodejs
  - ruby
  - nginx
  - redis_server
  - postgresql
  - certbot
  - mastodon
  - node_exporter
  - nginx_exporter

  - nginx_site_http_redirector
  - nginx_site_mastodon

  - postgresql_mastodon
