- hosts: internal

  roles:
  - dnsmasq
  - blackbox_exporter
  - prometheus
  - grafana

  - caddy
  - caddy_site_acme_server

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
