---
- hosts: all
  max_fail_percentage: 30

  roles:
  - logrotate
  - exim
  - apticron
  - node_exporter
  - nginx_exporter
  - certbot
  - fluentd
  - mc

  - nginx_site_local_proxy

  - fluentd_input_auth_log
  - fluentd_input_exim_log
  - fluentd_input_fail2ban_log
  - fluentd_input_nginx_log
  - fluentd_input_nftables_log

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: internal
  max_fail_percentage: 30

  roles:
  - minio
  - blackbox_exporter
  - grafana
  - grafana_provisioning
  - prometheus
  - elasticsearch
  - elasticsearch_exporter

  - minio_setup
  - elasticsearch_setup

  - nginx_site_minio_server
  - nginx_site_elasticsearch

  - fluentd_input_caddy_log

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: public
  max_fail_percentage: 30

  roles:
  - nodejs
  - ruby
  - redis_server
  - postgresql
  - redis_exporter
  - postgres_exporter
  - statsd_exporter

  - postgresql_dbsetup_mastodon
  - mastodon

  - postgresql_dbsetup_postgres_exporter
  - postgres_backup

  - nginx_site_mastodon_front
  - nginx_site_www_redirector
  - nginx_site_root_front

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: all
  max_fail_percentage: 30

  roles:
  - fluentd_output_elasticsearch

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
