- hosts: public

  roles:
  - nodejs
  - ruby
  - redis_server
  - postgresql
  - redis_exporter
  - postgres_exporter
  - statsd_exporter

  - postgresql_mastodon
  - mastodon

  - nginx_site_http_redirector
  - nginx_site_mastodon_front

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
