---
- hosts: public
  max_fail_percentage: 30

  roles:
  - nginx_site_mastodon_front
  - nginx_site_firefish_front
  - nginx_site_archivedon_front

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
