---
- hosts: all
  max_fail_percentage: 30

  roles:
  - logrotate
  - exim
  - apticron
  - node_exporter
  - nginx_exporter
  - certbot
  - fluent_bit
  - mc

  - nginx_site_local_proxy

  - fluent_bit_input_auth_log
  - fluent_bit_input_sshd_log
  - fluent_bit_input_sudo_log
  - fluent_bit_input_exim_log
  - fluent_bit_input_fail2ban_log
  - fluent_bit_input_nginx_log
  - fluent_bit_input_nftables_log

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: internal
  max_fail_percentage: 30

  roles:
  - minio
  - blackbox_exporter
  - grafana
  - grafana_provisioning
  - prometheus
  - elasticsearch
  - elasticsearch_exporter
  - mstdn_rss2bsky_post

  - minio_setup
  - elasticsearch_setup

  - fluent_bit_input_caddy_log

  - nginx_site_minio_server
  - nginx_site_elasticsearch

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: public
  max_fail_percentage: 30

  roles:
  - nodejs
  - ruby
  - redis_server
  - postgresql
  - redis_exporter
  - postgres_exporter
  - statsd_exporter

  - postgresql_dbsetup_mastodon
  - mastodon

  - postgresql_dbsetup_postgres_exporter
  - postgres_backup

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: all
  max_fail_percentage: 30

  roles:
  - fluent_bit_output_elasticsearch

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
