---
- hosts: all

  roles:
  - exim
  - apticron
  - node_exporter
  - nginx_exporter
  - certbot
  - nginx_site_local_proxy

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: internal

  roles:
  - minio
  - blackbox_exporter
  - grafana
  - grafana_provisioning
  - prometheus
  - elasticsearch

  - minio_setup
  - nginx_site_minio_server

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: public

  roles:
  - nodejs
  - ruby
  - redis_server
  - postgresql
  - redis_exporter
  - postgres_exporter
  - statsd_exporter

  - postgresql_mastodon
  - mastodon

  - postgresql_postgres_exporter

  - nginx_site_mastodon_front
  - nginx_site_www_redirector

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
