---
- hosts: all
  max_fail_percentage: 30

  roles:
  - systemd_resolved

  - nginx
  - nginx_site_http_redirector

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: internal
  max_fail_percentage: 30

  roles:
  - caddy
  - caddy_site_acme_server

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
