---
- hosts: all
  max_fail_percentage: 30

  roles:
  - base
  - systemd
  - network
  - sudo
  - ca_certs
  - workuser_setup
  - syslog
  - openssh_server

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
