- hosts: all

  roles:
  - base
  - nftables
  - fail2ban
  - openssh_server
  - nodejs
  - ruby
  - nginx
  - redis_server
  - postgresql
  - exim
  - certbot
  - private_ca
  - mastodon
  - node_exporter
  - nginx_exporter
  - prometheus
  - grafana

  - nginx_site_http_redirector
  - nginx_site_mastodon

  - postgresql_mastodon

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
