- hosts: all

  roles:
  - base
  - workuser_setup
  - nftables
  - fail2ban
  - apticron
  - openssh_server
  - node_exporter
  - exim
  - certbot
  - private_root_ca
  - nginx
  - nginx_site_http_redirector
  - nginx_site_local_proxy
  - nginx_exporter

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- import_playbook: ./playbook-internal.yml
- import_playbook: ./playbook-public.yml
