---
- hosts: all

  roles:
  - logrotate
  - exim
  - apticron
  - node_exporter
  - nginx_exporter
  - certbot
  - fluentd
  - nginx_site_local_proxy

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: internal

  roles:
  - minio
  - blackbox_exporter
  - grafana
  - grafana_provisioning
  - prometheus
  - elasticsearch
  - elasticsearch_exporter

  - minio_setup
  - elasticsearch_setup

  - nginx_site_minio_server
  - nginx_site_elasticsearch

  - fluentd_input_auth_log
  - fluentd_input_nginx_log
  - fluentd_output_elasticsearch

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check

- hosts: public

  roles:
  - nodejs
  - ruby
  - redis_server
  - postgresql
  - redis_exporter
  - postgres_exporter
  - statsd_exporter

  - postgresql_dbsetup_mastodon
  - mastodon

  - postgresql_dbsetup_postgres_exporter

  - nginx_site_mastodon_front
  - nginx_site_www_redirector

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
