---
- hosts: internal

  roles:
  - caddy
  - caddy_site_acme_server

  - nginx
  - nginx_site_http_redirector

  - postfix

  post_tasks:
  - name: Check
    ansible.builtin.command: echo check
    notify: Check
