package nginx_site_www_redirector

nginx_site_www_redirector_listen_port: uint
nginx_site_www_redirector_domain: string
nginx_site_www_redirector_url: string

nginx_site_www_redirector_acme_challenge_url: string
nginx_site_www_redirector_ca_bundle_path: string
