---
- name: Copy td-agent gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/td-agent-archive-keyring.gpg
    dest: /usr/share/keyrings/td-agent-archive-keyring.gpg
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install td-agent repository
  ansible.builtin.template:
    src: etc/apt/sources.list.d/td-agent.sources
    dest: /etc/apt/sources.list.d/td-agent.sources
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  register: fluentd_install_repository_result

- name: Install td-agent
  ansible.builtin.apt:
    name: 'td-agent={{ fluentd_td_agent_version }}*'
    state: present
    update_cache: '{{ fluentd_install_repository_result.changed }}'
  become: true
