package network

network_public_iface: string
network_public_ipv4_gateway?: string
network_public_ipv4_netmask: string
network_public_ipv4_nameserver: string
network_public_ipv4_search: string
network_public_ipv6_gateway?: string
network_public_ipv6_netmask: string
network_public_ipv6_nameserver: string
network_public_ipv6_search: string

network_internal_iface: string
network_internal_ipv4_netmask: string
network_internal_ipv4_nameserver: string
network_internal_ipv4_search: string
