---
- name: Copy gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/groonga-archive-keyring.gpg
    dest: /usr/share/keyrings/groonga-archive-keyring.gpg
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install repository
  ansible.builtin.template:
    src: etc/apt/sources.list.d/groonga.sources
    dest: /etc/apt/sources.list.d/groonga.sources
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  register: pgroonga_install_repository_result

- name: Install pgroonga
  ansible.builtin.apt:
    name: 'postgresql-{{ postgresql_major_version }}-pgdg-pgroonga={{ pgroonga_version }}*'
    state: present
    update_cache: '{{ pgroonga_install_repository_result.changed }}'
  become: true
