package nginx_site_mastodon_front

nginx_site_mastodon_front_listen_port: uint
mastodon_local_domain: string

mastodon_streaming_listen_port: uint
mastodon_web_listen_port: uint

nginx_site_mastodon_front_acme_challenge_url: string
nginx_site_mastodon_front_ca_bundle_path: string
