---
- name: Install logrotate
  ansible.builtin.apt:
    name: 'logrotate={{ logrotate_version }}*'
    state: present
  become: true

- name: Install logrotate timer
  ansible.builtin.template:
    src: usr/lib/systemd/system/logrotate.timer
    dest: /usr/lib/systemd/system/logrotate.timer
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
  - Reload logrotate.timer
