---
- name: Install logrotate
  ansible.builtin.apt:
    name: 'logrotate={{ logrotate_version }}*'
    state: present
  become: true

- name: Directory of links is available
  ansible.builtin.file:
    path: /etc/logrotate-available.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/logrotate.timer.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override timer
  ansible.builtin.template:
    src: etc/systemd/system/logrotate.timer.d/override.conf
    dest: /etc/systemd/system/logrotate.timer.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate -t timer %s
  become: true
  notify:
  - Reload logrotate.timer

- name: Validate systemd timer
  ansible.builtin.command: |
    /opt/bin/systemd-validate -t timer /lib/systemd/system/logrotate.timer
  become: true
  changed_when: false
  register: logrotate_systemd_validate_result
  failed_when: |
    logrotate_systemd_validate_result.rc != 0
    or logrotate_systemd_validate_result.stderr != ''

- name: Install logrotate validate
  ansible.builtin.copy:
    src: opt/bin/logrotate-validate
    dest: /opt/bin/logrotate-validate
    owner: root
    group: root
    mode: '0755'
    backup: true
  become: true

- name: Install logrotate backup
  ansible.builtin.copy:
    src: opt/bin/logrotate-backup
    dest: /opt/bin/logrotate-backup
    owner: root
    group: root
    mode: '0755'
    backup: true
  become: true

- name: Start logrotate if not started
  ansible.builtin.command:
    cmd: systemctl start logrotate
    creates: /var/lib/logrotate/status
  become: true
