---
- name: Install logrotate
  ansible.builtin.apt:
    name: 'logrotate={{ logrotate_version }}*'
    state: present
  become: true

- name: Install logrotate validate
  ansible.builtin.copy:
    src: opt/bin/logrotate-validate
    dest: /opt/bin/logrotate-validate
    owner: root
    group: root
    mode: '0755'
    backup: true
  become: true

- name: Directory of links is available
  ansible.builtin.file:
    path: /etc/logrotate-available.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install logrotate timer
  ansible.builtin.template:
    src: usr/lib/systemd/system/logrotate.timer
    dest: /usr/lib/systemd/system/logrotate.timer
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
  - Reload logrotate.timer
