---
- name: Select users
  ansible.builtin.command:
    cmd: |
      sudo --user postgres psql
        --command 'SELECT usename FROM pg_shadow;'
        --csv
  become: true
  changed_when: false
  register: postgresql_mastodon_users_result

- name: Mastodon working user for Mastodon DB is available
  ansible.builtin.command:
    cmd: |
      sudo --user postgres psql
        --command "
          CREATE USER {{ mastodon_db_user_name }}
          WITH ENCRYPTED PASSWORD 'md5{{ mastodon_db_user_password | md5 }}'
          CREATEDB;
        "
  become: true
  when: |
    mastodon_db_user_name not in postgresql_mastodon_users_result.stdout_lines
