---
- name: Reload fail2ban
  ansible.builtin.set_fact:
    fail2ban_handler_state: reloaded
  become: true
  listen: Reload fail2ban

- name: Restart fail2ban
  ansible.builtin.set_fact:
    fail2ban_handler_state: restarted
  become: true
  listen: Restart fail2ban

- name: Restart or reload fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: '{{ fail2ban_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart fail2ban
  - Reload fail2ban

- name: Check systemd service
  ansible.builtin.command: systemctl status fail2ban
  become: true
  changed_when: false
  listen: Check
