---
- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart fail2ban

- name: Check systemd service
  ansible.builtin.command: systemctl status fail2ban
  become: true
  changed_when: false
  listen: Check
