---
- name: Install output config to ElasticSearch
  ansible.builtin.template:
    src: etc/fluent-bit/output-conf.d/elasticsearch_xxx.conf
    dest: '/etc/fluent-bit/output-conf.d/elasticsearch_{{ item }}.conf'
    owner: root
    group: root
    mode: '0640'
    backup: true
    validate: /opt/bin/fluent-bit-validate %s
  diff: false
  become: true
  loop: '{{ fluent_bit_output_elasticsearch_entries|dict2items|map(attribute="key") }}'
  notify:
  - Restart fluent-bit
