{
 "title": "FluentBit Stats",
 "tags": [
  "Prometheus",
  "fluent-bit"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(fluentbit_uptime,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fluentbit_uptime{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{instance=~\"$instance\"} [1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_total{instance=~\"$instance\"} [1m]))",
     "legendFormat": "retry"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{instance=~\"$instance\"} [1m]))",
     "legendFormat": "retry failed"
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{instance=~\"$instance\"} [1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{instance=~\"$instance\"} [1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Files Open Count [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_input_files_opened_total{instance=~\"$instance\"} [10m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Files Rotate Count [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_input_files_rotated_total{instance=~\"$instance\"} [10m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{instance=~\"$instance\"} [1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{instance=~\"$instance\"} [1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}