{
 "title": "MinIO Stats",
 "tags": [ "MinIO" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "minio_cluster_disk_total", "legendFormat": "total" },
    {
     "expr": "minio_cluster_disk_online_total",
     "legendFormat": "online"
    },
    {
     "expr": "minio_cluster_disk_offline_total",
     "legendFormat": "offline"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(minio_s3_requests_total[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(minio_s3_requests_waiting_total[1m])",
     "legendFormat": "waiting"
    },
    {
     "expr": "rate(minio_s3_requests_incoming_total[1m])",
     "legendFormat": "incoming"
    },
    {
     "expr": "rate(minio_s3_requests_inflight_total[1m])",
     "legendFormat": "inflight"
    }
   ]
  },
  {
   "title": "Rejected Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(minio_s3_requests_rejected_auth_total[1m])",
     "legendFormat": "auth"
    },
    {
     "expr": "rate(minio_s3_requests_rejected_header_total[1m])",
     "legendFormat": "header"
    },
    {
     "expr": "rate(minio_s3_requests_rejected_invalid_total[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(minio_s3_requests_rejected_timestamp_total[1m])",
     "legendFormat": "timestamp"
    }
   ]
  }
 ]
}