{
 "title": "Nginx Exporter",
 "tags": [
  "nginx-exporter",
  "Nginx",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginx_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_up{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{instance=~\"$instance\"}[10m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted[1m]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(nginx_connections_waiting[1m]))",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(rate(nginx_connections_handled[1m]))",
     "legendFormat": "handled"
    },
    {
     "expr": "sum(rate(nginx_connections_reading[1m]))",
     "legendFormat": "reading"
    },
    {
     "expr": "sum(rate(nginx_connections_writing[1m]))",
     "legendFormat": "writing"
    },
    {
     "expr": "sum(rate(nginx_connections_active[1m]))",
     "legendFormat": "active"
    }
   ]
  }
 ]
}