{
 "title": "StatsD Exporter",
 "tags": [
  "StatsD",
  "statsd-exporter",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(statsd_exporter_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Loaded Mappings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(statsd_exporter_loaded_mappings{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lines Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(statsd_exporter_lines_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Samples Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(statsd_exporter_samples_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Connections [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(statsd_exporter_tcp_connections_total{instance=~\"$instance\"}[10m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(statsd_exporter_tcp_connection_errors_total{instance=~\"$instance\"}[10m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "UDP Packets [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(statsd_exporter_udp_packets_total{instance=~\"$instance\"}[10m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Unix-gram Packets [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(statsd_exporter_unixgram_packets_total{instance=~\"$instance\"}[10m]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}