{
 "title": "StatsD Exporter: Mastodon",
 "tags": [
  "StatsD",
  "statsd-exporter",
  "Mastodon",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SideKiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mastodon_sidekiq_processes_size",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Worker Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mastodon_sidekiq_workers_size", "legendFormat": "total" }
   ]
  },
  {
   "title": "Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(mastodon_sidekiq_processed [10m]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(rate(mastodon_sidekiq_failed [10m]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(mastodon_sidekiq_enqueued [10m]))",
     "legendFormat": "enqueued"
    }
   ]
  },
  {
   "title": "Job Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(mastodon_sidekiq_dead_size [10m]))",
     "legendFormat": "dead"
    },
    {
     "expr": "sum(rate(mastodon_sidekiq_retry_size [10m]))",
     "legendFormat": "retry"
    },
    {
     "expr": "sum(rate(mastodon_sidekiq_scheduled_size [10m]))",
     "legendFormat": "scheduled"
    }
   ]
  },
  {
   "title": "Success Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(mastodon_sidekiq_success [10m])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(mastodon_sidekiq_processing_time_sum [1m])) by (event)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(mastodon_web_status[10m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Endpoint Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "rate(mastodon_web_status[10m])", "legendFormat": "{{api}}:{{status}}" }
   ]
  },
  {
   "title": "View Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(mastodon_web_view_time_sum[10m])",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "DB time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "rate(mastodon_web_db_time_sum[10m])",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "rate(mastodon_web_total_duration_sum[10m])",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}