---
- name: Copy nodesource gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/nodesource.gpg
    dest: /usr/share/keyrings/nodesource.gpg
  become: true

- name: Install nodesource repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main'
    state: present
  become: true

- name: Install nodejs
  ansible.builtin.apt:
    name: 'nodejs={{ nodejs_version }}*'
    state: present
  become: true
