---
- name: Copy nodesource gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/nodesource.gpg
    dest: /usr/share/keyrings/nodesource.gpg
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install nodesource repository
  ansible.builtin.template:
    copy: etc/apt/sources.list.d/nodesource.list
    dest: /etc/apt/sources.list.d/nodesource.list
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install nodejs
  ansible.builtin.apt:
    name: 'nodejs={{ nodejs_version }}*'
    state: present
  become: true
