---
- name: Restart firefish
  ansible.builtin.systemd:
    name: firefish
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart firefish

- name: Check systemd service
  ansible.builtin.command: systemctl status firefish
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    host: '::1'
    port: '{{ firefish_listen_port }}'
    state: started
    timeout: 60
  listen: Check
