---
- name: Directory of provisioning available is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available
    state: directory
    owner: root
    group: grafana
    mode: '0750'
  become: true

- name: Directory of available datasources is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available/datasources
    state: directory
    owner: root
    group: grafana
    mode: '0750'
  become: true

- name: Directory of available datasources is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available/dashboards
    state: directory
    owner: root
    group: grafana
    mode: '0750'
  become: true

- name: Directory of provisioning available is available
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: '0750'
  become: true

- name: Copy datasource
  ansible.builtin.template:
    src: etc/grafana/prov-available/datasources/datasource.yml
    dest: /etc/grafana/prov-available/datasources/datasource.yml
    owner: root
    group: grafana
    mode: '0640'
    backup: true
  become: true
  notify:
  - Restart grafana

- name: Copy dashboard providers of generic folder
  ansible.builtin.template:
    src: etc/grafana/prov-available/dashboards/generic.yml
    dest: /etc/grafana/prov-available/dashboards/generic.yml
    owner: root
    group: grafana
    mode: '0640'
    backup: true
  become: true
  notify:
  - Restart grafana

- name: Copy dashboard providers of alert folder
  ansible.builtin.template:
    src: etc/grafana/prov-available/dashboards/alert.yml
    dest: /etc/grafana/prov-available/dashboards/alert.yml
    owner: root
    group: grafana
    mode: '0640'
    backup: true
  become: true
  notify:
  - Restart grafana

- name: Set dashboards
  set_fact:
    grafana_provisioning_dashboards:
      - node-exporter
      - alert-prometheus-scraping

- name: Copy dashboards
  ansible.builtin.copy:
    src: var/lib/grafana/dashboards/{{ item }}.json
    dest: /var/lib/grafana/dashboards/{{ item }}.json
    owner: grafana
    group: grafana
    mode: '0640'
    backup: true
  become: true
  loop: '{{ grafana_provisioning_dashboards }}'
  notify:
  - Restart grafana

- name: Enable datasource
  ansible.builtin.file:
    src: /etc/grafana/prov-available/datasources/datasource.yml
    dest: /etc/grafana/provisioning/datasources/datasource.yml
    state: link
  become: true
  notify:
  - Restart grafana

- name: Enable dashboards of generic folder
  ansible.builtin.file:
    src: /etc/grafana/prov-available/dashboards/generic.yml
    dest: /etc/grafana/provisioning/dashboards/generic.yml
    state: link
  become: true
  notify:
  - Restart grafana

- name: Enable dashboards of alert folder
  ansible.builtin.file:
    src: /etc/grafana/prov-available/dashboards/alert.yml
    dest: /etc/grafana/provisioning/dashboards/alert.yml
    state: link
  become: true
  notify:
  - Restart grafana
