---
- name: Directory of provisioning available is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available
    state: directory
    owner: root
    group: grafana
    mode: '0750'
  become: true

- name: Directory of available datasources is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available/datasources
    state: directory
    owner: root
    group: grafana
    mode: '0750'
  become: true

- name: Directory of available dashboards provisioning is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available/dashboards
    state: directory
    owner: root
    group: grafana
    mode: '0750'
  become: true

- name: Directory of available alertings is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available/alerting
    state: directory
    owner: root
    group: grafana
    mode: '0750'
  become: true

- name: Directory of available notifiers is available
  ansible.builtin.file:
    path: /etc/grafana/prov-available/notifiers
    state: directory
    owner: grafana
    group: grafana
    mode: '0750'
  become: true

- name: Directory of available dashboards is available
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: '0750'
  become: true

- name: Copy datasource
  ansible.builtin.template:
    src: etc/grafana/prov-available/datasources/datasource.yml
    dest: /etc/grafana/prov-available/datasources/datasource.yml
    owner: root
    group: grafana
    mode: '0640'
    backup: true
  become: true
  diff: false
  notify:
  - Restart grafana

- name: Copy dashboard providers of generic folder
  ansible.builtin.template:
    src: etc/grafana/prov-available/dashboards/generic.yml
    dest: /etc/grafana/prov-available/dashboards/generic.yml
    owner: root
    group: grafana
    mode: '0640'
    backup: true
  become: true
  notify:
  - Restart grafana

- name: Set dashboards
  set_fact:
    grafana_provisioning_dashboards:
      - prometheus-stats
      - grafana-stats
      - node-exporter
      - minio-stats
      - postgres-exporter
      - nginx-exporter
      - redis-exporter
      - elasticsearch-exporter
      - blackbox-exporter
      - fluent-bit-stats
      - log-authentications
      - log-nftables
      - log-nginx
      - log-sshd
      - log-sudo

    grafana_provisioning_alertings:
      - prometheus
      - node-exporter
      - fluent-bit-stats
      - blackbox-exporter
      - elasticsearch-exporter
      - nginx-exporter
      - postgres-exporter
      - redis-exporter

- name: Copy dashboards
  ansible.builtin.copy:
    src: var/lib/grafana/dashboards/{{ item }}.json
    dest: /var/lib/grafana/dashboards/{{ item }}.json
    owner: grafana
    group: grafana
    mode: '0640'
    backup: true
  become: true
  loop: '{{ grafana_provisioning_dashboards }}'
  notify:
  - Restart grafana

- name: Copy alertings
  ansible.builtin.template:
    src: 'etc/grafana/prov-available/alerting/{{ item }}.yml'
    dest: '/etc/grafana/prov-available/alerting/{{ item }}.yml'
    owner: grafana
    group: grafana
    mode: '0640'
    backup: true
  become: true
  loop: '{{ grafana_provisioning_alertings }}'
  notify:
  - Restart grafana

- name: Copy notifiers of generic folder
  ansible.builtin.template:
    src: etc/grafana/prov-available/notifiers/generic.yml
    dest: /etc/grafana/prov-available/notifiers/generic.yml
    owner: root
    group: grafana
    mode: '0640'
    backup: true
  become: true
  notify:
  - Restart grafana

- name: Enable datasource
  ansible.builtin.file:
    src: /etc/grafana/prov-available/datasources/datasource.yml
    dest: /etc/grafana/provisioning/datasources/datasource.yml
    state: link
  become: true
  notify:
  - Restart grafana

- name: Enable dashboards of generic folder
  ansible.builtin.file:
    src: /etc/grafana/prov-available/dashboards/generic.yml
    dest: /etc/grafana/provisioning/dashboards/generic.yml
    state: link
  become: true
  notify:
  - Restart grafana

- name: Enable alertings
  ansible.builtin.file:
    src: '/etc/grafana/prov-available/alerting/{{ item }}.yml'
    dest: '/etc/grafana/provisioning/alerting/{{ item }}.yml'
    state: link
  become: true
  loop: '{{ grafana_provisioning_alertings }}'
  notify:
  - Restart grafana

- name: Enable notifiers
  ansible.builtin.file:
    src: /etc/grafana/prov-available/notifiers/generic.yml
    dest: /etc/grafana/provisioning/notifiers/generic.yml
    state: link
  become: true
  notify:
  - Restart grafana
