---
- name: Install openssh-server
  ansible.builtin.apt:
    name: 'openssh-server=1:{{ openssh_server_version }}*'
    state: present
  become: true

- name: Copy sshd server config
  ansible.builtin.template:
    src: etc/ssh/sshd_config.d/server.conf
    dest: /etc/ssh/sshd_config.d/server.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: sshd -T -f %s
  become: true
  notify:
    - Reload openssh_server

- name: Copy sshd auth config
  ansible.builtin.copy:
    src: etc/ssh/sshd_config.d/auth.conf
    dest: /etc/ssh/sshd_config.d/auth.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: sshd -T -f %s
  become: true
  notify:
    - Reload openssh_server

- name: Copy sshd syslog facility config
  ansible.builtin.copy:
    src: etc/ssh/sshd_config.d/syslog_facility.conf
    dest: /etc/ssh/sshd_config.d/syslog_facility.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: sshd -T -f %s
  become: true
  notify:
    - Reload openssh_server

- name: Copy syslog config
  ansible.builtin.copy:
    src: etc/rsyslog.d/sshd.conf
    dest: /etc/rsyslog.d/sshd.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart syslog

- name: Create SSHd log file if needed
  ansible.builtin.command:
    cmd: touch /var/log/sshd.log
    creates: /var/log/sshd.log
  become: true

- name: Make correct permissions of log file
  ansible.builtin.file:
    path: /var/log/sshd.log
    state: file
    owner: root
    group: adm
    mode: '0640'
  become: true

- name: Install logrotate config
  ansible.builtin.template:
    src: etc/logrotate-available.d/sshd
    dest: /etc/logrotate-available.d/sshd
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/logrotate-validate %s
  become: true

- name: Enable logrotate config
  ansible.builtin.file:
    src: /etc/logrotate-available.d/sshd
    dest: /etc/logrotate.d/sshd
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Notify restart openssh_server if not started
  ansible.builtin.command: systemctl status ssh
  become: true
  register: openssh_server_service_status
  changed_when: openssh_server_service_status.rc != 0
  failed_when: false
  notify:
    - Restart openssh_server
