---
- name: Install openssh-server
  ansible.builtin.apt:
    name: 'openssh-server=1:{{ openssh_server_version }}*'
    state: present
  become: true

- name: Copy sshd server config
  ansible.builtin.template:
    src: etc/ssh/sshd_config.d/server.conf
    dest: /etc/ssh/sshd_config.d/server.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart openssh_server

- name: Copy sshd auth config
  ansible.builtin.copy:
    src: etc/ssh/sshd_config.d/auth.conf
    dest: /etc/ssh/sshd_config.d/auth.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart openssh_server

- name: Notify restart openssh_server if not started
  ansible.builtin.command: systemctl status ssh
  become: true
  register: openssh_server_service_status
  changed_when: openssh_server_service_status.rc != 0
  failed_when: false
  notify:
    - Restart openssh_server
