---
- name: Install exim
  ansible.builtin.apt:
    name: 'exim4={{ exim_version }}*'
    state: present
  become: true

- name: Install logrotate config
  ansible.builtin.template:
    src: etc/logrotate-available.d/exim4-base
    dest: /etc/logrotate-available.d/exim4-base
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/logrotate-validate %s
  become: true

- name: Enable logrotate config
  ansible.builtin.file:
    src: /etc/logrotate-available.d/exim4-base
    dest: /etc/logrotate.d/exim4-base
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Copy exim config
  ansible.builtin.template:
    src: etc/exim4/update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart exim

- name: Copy password file
  ansible.builtin.template:
    src: etc/exim4/passwd.client
    dest: /etc/exim4/passwd.client
    owner: root
    group: Debian-exim
    mode: '0640'
    backup: true
  become: true
  diff: false
  notify:
    - Restart exim

- name: Notify restart exim if not started
  ansible.builtin.command: systemctl status exim4
  become: true
  register: exim_service_status
  changed_when: exim_service_status.rc != 0
  failed_when: false
  notify:
    - Restart exim
