---
- name: Install postgresql exporter
  ansible.builtin.apt:
    name: 'prometheus-postgres-exporter={{ postgres_exporter_version }}*'
    state: present
  become: true

- name: Copy postgres exporter environment
  ansible.builtin.template:
    src: etc/default/prometheus-postgres-exporter
    dest: /etc/default/prometheus-postgres-exporter
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart postgres-exporter

- name: Copy postgres exporter private environment
  ansible.builtin.template:
    src: etc/default/prometheus-postgres-exporter.private
    dest: /etc/default/prometheus-postgres-exporter.private
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  diff: false
  notify:
    - Restart postgres-exporter

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus-postgres-exporter.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override service
  ansible.builtin.template:
    src: etc/systemd/system/prometheus-postgres-exporter.service.d/override.conf
    dest: /etc/systemd/system/prometheus-postgres-exporter.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  notify:
    - Restart postgres-exporter

- name: Validate systemd service
  ansible.builtin.command: |
    /opt/bin/systemd-validate /lib/systemd/system/prometheus-postgres-exporter.service
  become: true
  changed_when: false
  register: postgres_exporter_systemd_validate_result
  failed_when: |
    postgres_exporter_systemd_validate_result.rc != 0
    or postgres_exporter_systemd_validate_result.stderr != ''

- name: Notify restart postgres exporter if not started
  ansible.builtin.command: systemctl status prometheus-postgres-exporter
  become: true
  register: postgres_exporter_service_status
  changed_when: postgres_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart postgres-exporter
