---
- name: Directory of PKI is available
  ansible.builtin.file:
    path: /etc/pki
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of private CA is available
  ansible.builtin.file:
    path: /etc/pki/private_ca
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Set path of private CA certificate
  ansible.builtin.set_fact:
    private_root_ca_certificate_path: /etc/pki/private_ca/rootCA_cert.pem

- name: Install private CA certificate
  ansible.builtin.copy:
    content: '{{ private_root_ca_certificate }}'
    dest: '{{ private_root_ca_certificate_path }}'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
