---
- name: mcli is available
  ansible.builtin.apt:
    name: 'mcli={{ mc_version }}'
    state: present
  become: true
  failed_when: false
  register: mc_installed_check

- name: Install mcli
  ansible.builtin.apt:
    deb: '{{ mc_deb_url }}'
    state: present
  become: true
  when: |
    'msg' in mc_installed_check and mc_installed_check.msg is search('No package')

- name: Directory of mcli config is available
  ansible.builtin.file:
    path: /etc/mcli-public
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Setup mc configs
  ansible.builtin.command:
    cmd: mcli --config-dir /etc/mcli-public alias ls
    creates: /etc/mcli-public/config.json
  become: true

- name: mcli config is available
  ansible.builtin.file:
    path: /etc/mcli-public/config.json
    state: file
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Directory of mcli certs is available
  ansible.builtin.file:
    path: /etc/mcli-public/certs
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of mcli CAs is available
  ansible.builtin.file:
    path: /etc/mcli-public/certs/CAs
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install private CA for mc
  ansible.builtin.file:
    src: '{{ ca_certs_bundle_file_with_private_ca }}'
    dest: /etc/mcli-public/certs/CAs/ca-certificates.crt
    owner: root
    group: root
    state: link
  become: true
