---
- name: Install redis exporter
  ansible.builtin.apt:
    name: 'prometheus-redis-exporter={{ redis_exporter_version }}*'
    state: present
  become: true

- name: Directory of redis exporter is available
  ansible.builtin.file:
    path: /etc/redis_exporter
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: true

- name: Copy redis exporter environment
  ansible.builtin.template:
    src: etc/default/prometheus-redis-exporter
    dest: /etc/default/prometheus-redis-exporter
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  diff: false
  notify:
    - Restart redis-exporter

- name: Install redis exporter service
  ansible.builtin.template:
    src: usr/lib/systemd/system/prometheus-redis-exporter.service
    dest: /usr/lib/systemd/system/prometheus-redis-exporter.service
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart redis-exporter

- name: Notify restart redis exporter if not started
  ansible.builtin.command: systemctl status prometheus-redis-exporter
  become: true
  register: redis_exporter_service_status
  changed_when: redis_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart redis-exporter
