---
- name: Install redis exporter
  ansible.builtin.apt:
    name: 'prometheus-redis-exporter={{ redis_exporter_version }}*'
    state: present
  become: true

- name: Directory of redis exporter is available
  ansible.builtin.file:
    path: /etc/redis_exporter
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: true

- name: Copy redis exporter environment
  ansible.builtin.template:
    src: etc/default/prometheus-redis-exporter
    dest: /etc/default/prometheus-redis-exporter
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart redis-exporter

- name: Copy redis exporter private environment
  ansible.builtin.template:
    src: etc/default/prometheus-redis-exporter.private
    dest: /etc/default/prometheus-redis-exporter.private
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  diff: false
  notify:
    - Restart redis-exporter

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus-redis-exporter.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override service
  ansible.builtin.template:
    src: etc/systemd/system/prometheus-redis-exporter.service.d/override.conf
    dest: /etc/systemd/system/prometheus-redis-exporter.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  notify:
    - Restart redis-exporter

- name: Validate systemd service
  ansible.builtin.command: |
    /opt/bin/systemd-validate /lib/systemd/system/prometheus-redis-exporter.service
  become: true
  changed_when: false
  register: redis_exporter_systemd_validate_result
  failed_when: |
    redis_exporter_systemd_validate_result.rc != 0
    or redis_exporter_systemd_validate_result.stderr != ''

- name: Notify restart redis exporter if not started
  ansible.builtin.command: systemctl status prometheus-redis-exporter
  become: true
  register: redis_exporter_service_status
  changed_when: redis_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart redis-exporter
