---
- name: Restart nginx-exporter
  ansible.builtin.systemd:
    name: prometheus-nginx-exporter
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart nginx-exporter

- name: Check systemd service
  ansible.builtin.command: systemctl status prometheus-nginx-exporter
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ nginx_exporter_listen_port }}'
    state: started
    timeout: 60
  listen: Check
