---
- name: Reload nginx exporter
  ansible.builtin.set_fact:
    nginx_exporter_handler_state: reloaded
  become: true
  listen: Reload nginx-exporter

- name: Restart nginx exporter
  ansible.builtin.set_fact:
    nginx_exporter_handler_state: restarted
  become: true
  listen: Restart nginx-exporter

- name: Restart or reload nginx exporter
  ansible.builtin.systemd:
    name: prometheus-nginx-exporter
    state: '{{ nginx_exporter_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart nginx-exporter
  - Reload nginx-exporter

- name: Check systemd service
  ansible.builtin.command: systemctl status prometheus-nginx-exporter
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    host: '::1'
    port: '{{ nginx_exporter_listen_port }}'
    state: started
    timeout: 60
  listen: Check
