---
- name: Install openssl
  ansible.builtin.apt:
    name: 'openssl={{ openssl_version }}*'
    state: present
  become: true

- name: Add ocsp-responder user
  ansible.builtin.user:
    name: ocsp-responder
    system: true
    home: /var/lib/ocsp-responder
    shell: /usr/sbin/nologin
    state: present
  become: true

- name: Directory of OCSP PKIs is available
  ansible.builtin.file:
    path: /etc/pki/ocsp
    state: directory
    owner: ocsp-responder
    group: ocsp-responder
    mode: '0755'
  become: true

- name: Directories of OCSP entries are available
  ansible.builtin.file:
    path: '/etc/pki/ocsp/{{ item.key }}'
    state: directory
    owner: ocsp-responder
    group: ocsp-responder
    mode: '0755'
  become: true
  loop: '{{ openssl_ocsp_responder_entries|dict2items }}'

- name: Copy database contents
  ansible.builtin.copy:
    content: '{{ item.value.database_content }}'
    dest: '/etc/pki/ocsp/{{ item.key }}/index.txt'
    owner: ocsp-responder
    group: ocsp-responder
    mode: '0644'
    backup: true
  become: true
  loop: '{{ openssl_ocsp_responder_entries|dict2items }}'
  notify:
    - Restart openssl-ocsp-responder

- name: Copy certificates
  ansible.builtin.copy:
    content: '{{ item.value.ca_cert }}'
    dest: '/etc/pki/ocsp/{{ item.key }}/cacert.pem'
    owner: ocsp-responder
    group: ocsp-responder
    mode: '0644'
    backup: true
  become: true
  loop: '{{ openssl_ocsp_responder_entries|dict2items }}'
  notify:
    - Restart openssl-ocsp-responder

- name: Copy private keys
  ansible.builtin.copy:
    content: '{{ item.value.ca_privkey }}'
    dest: '/etc/pki/ocsp/{{ item.key }}/privkey.pem'
    owner: ocsp-responder
    group: ocsp-responder
    mode: '0600'
    backup: true
  become: true
  loop: '{{ openssl_ocsp_responder_entries|dict2items }}'
  notify:
    - Restart openssl-ocsp-responder

- name: Install sysconfig
  ansible.builtin.template:
    src: etc/default/openssl-ocsp-responder-xxx
    dest: '/etc/default/openssl-ocsp-responder-{{ item.key }}'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  loop: '{{ openssl_ocsp_responder_entries|dict2items }}'
  notify:
    - Restart openssl-ocsp-responder

- name: Install services
  ansible.builtin.template:
    src: etc/systemd/system/openssl-ocsp-responder-xxx.service
    dest: '/etc/systemd/system/openssl-ocsp-responder-{{ item.key }}.service'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  loop: '{{ openssl_ocsp_responder_entries|dict2items }}'
  notify:
    - Restart openssl-ocsp-responder
