---
- name: Restart redis-server
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart redis-server

- name: Check systemd service
  ansible.builtin.command: systemctl status redis-server
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ redis_server_listen_port }}'
    state: started
  listen: Check
