#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

CA_DIR="$(cd "$(dirname "$0")" && pwd)"

INTER_TLS_CA_DIR="$CA_DIR/interCA_TLS"

function show_usage() {
  cat <<EOS
Usage: $0 --dist-dir PATH
EOS
}

while [ "$#" -ne 0 ]; do
  case "$1" in
    '--dist-dir' )
      DIST_DIR="$2"
      shift
      ;;
    '-?' | '--help' )
      show_usage
      exit
      ;;
    * )
      echo "Unknown option: $1" 1>&2
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "${DIST_DIR:-}" ]; then
  echo "Not enough arguments." 1>&2
  show_usage
  exit 1
fi

mkdir -p "$DIST_DIR"
DIST_DIR="$(cd "$DIST_DIR" && pwd)"

OUT_CSR="$DIST_DIR/cert.csr"
OUT_CERT="$DIST_DIR/cert.pem"
OUT_FULLCHAIN="$DIST_DIR/fullchain.pem"
OUT_CHAIN="$DIST_DIR/chain.pem"
OUT_KEY="$DIST_DIR/privkey.pem"

openssl req \
  -config "$CA_DIR/req.cnf" \
  -newkey EC \
  -pkeyopt ec_paramgen_curve:prime256v1 \
  -nodes \
  -out "$OUT_CSR" \
  -keyout "$OUT_KEY"

cd "$CA_DIR" && openssl ca \
  -config "$INTER_TLS_CA_DIR/ca.cnf" \
  -notext \
  -batch \
  -in "$OUT_CSR" \
  -out "$OUT_CERT"

cp "$INTER_TLS_CA_DIR/cacert.pem" "$OUT_CHAIN"

cat "$OUT_CERT" "$OUT_CHAIN" > "$OUT_FULLCHAIN"
