---
- name: Install blackbox exporter
  ansible.builtin.apt:
    name: 'prometheus-blackbox-exporter={{ blackbox_exporter_version }}*'
    state: present
  become: true

- name: Get capabilities of blackbox exporter
  ansible.builtin.command:
    cmd: getcap /usr/bin/prometheus-blackbox-exporter
  become: true
  changed_when: false
  register: blackbox_exporter_current_caps_result

- name: Allow ping to blackbox exporter
  community.general.capabilities:
    path: /usr/bin/prometheus-blackbox-exporter
    capability: cap_net_raw=ep
    state: present
  become: true
  when: |
    not blackbox_exporter_current_caps_result.stdout is search('cap_net_raw=ep')
  notify:
    - Restart blackbox-exporter

- name: Backup original logrotate config
  ansible.builtin.command:
    cmd: /opt/bin/logrotate-backup prometheus-blackbox-exporter
  changed_when: false
  become: true

- name: Install logrotate config
  ansible.builtin.template:
    src: etc/logrotate-available.d/prometheus-blackbox-exporter
    dest: /etc/logrotate-available.d/prometheus-blackbox-exporter
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/logrotate-validate %s
  become: true

- name: Enable logrotate config
  ansible.builtin.file:
    src: /etc/logrotate-available.d/prometheus-blackbox-exporter
    dest: /etc/logrotate.d/prometheus-blackbox-exporter
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Copy blackbox exporter environment
  ansible.builtin.template:
    src: etc/default/prometheus-blackbox-exporter
    dest: /etc/default/prometheus-blackbox-exporter
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart blackbox-exporter

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus-blackbox-exporter.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override service
  ansible.builtin.template:
    src: etc/systemd/system/prometheus-blackbox-exporter.service.d/override.conf
    dest: /etc/systemd/system/prometheus-blackbox-exporter.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  notify:
    - Restart blackbox-exporter

- name: Copy blackbox exporter config
  ansible.builtin.template:
    src: etc/prometheus/blackbox.yml
    dest: /etc/prometheus/blackbox.yml
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /usr/bin/prometheus-blackbox-exporter --config.check --config.file %s
  become: true
  notify:
    - Reload blackbox-exporter

- name: Notify restart blackbox exporter if not started
  ansible.builtin.command: systemctl status prometheus-blackbox-exporter
  become: true
  register: blackbox_exporter_service_status
  changed_when: blackbox_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart blackbox-exporter
