---
- name: Directory of certificates is available
  ansible.builtin.file:
    path: '/etc/letsencrypt/live'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of private certificate is available
  ansible.builtin.file:
    path: '/etc/letsencrypt/live/{{ mastodon_local_domain }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: fullchain certificate is available
  ansible.builtin.copy:
    content: "{{ private_mastodon_certificate_fullchain }}\n"
    dest: '/etc/letsencrypt/live/{{ mastodon_local_domain }}/fullchain.pem'
    state: file
    owner: root
    group: root
    mode: '0644'
  become: true

- name: chain certificate is available
  ansible.builtin.copy:
    content: "{{ private_mastodon_certificate_chain }}\n"
    dest: '/etc/letsencrypt/live/{{ mastodon_local_domain }}/chain.pem'
    state: file
    owner: root
    group: root
    mode: '0644'
  become: true

- name: private key is available
  ansible.builtin.copy:
    content: "{{ private_mastodon_certificate_privkey }}\n"
    dest: '/etc/letsencrypt/live/{{ mastodon_local_domain }}/privkey.pem'
    state: file
    owner: root
    group: root
    mode: '0600'
  become: true
