---
- name: Install postgres dump script
  ansible.builtin.copy:
    src: usr/local/bin/postgres-archive-dump
    dest: /usr/local/bin/postgres-archive-dump
    owner: root
    group: root
    mode: '0755'
    backup: true
  become: true

- name: Install postgres backup script
  ansible.builtin.copy:
    src: usr/local/bin/postgres-backup
    dest: /usr/local/bin/postgres-backup
    owner: root
    group: root
    mode: '0755'
    backup: true
  become: true
