---
- name: Check internal host variable is required
  ansible.builtin.debug:
    var: 'network_internal_hostname'

- name: Directory of interfaces is available
  ansible.builtin.file:
    path: /etc/network/iface-available.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install internal iface
  ansible.builtin.template:
    src: etc/network/iface-available.d/internal_iface.conf
    dest: '/etc/network/iface-available.d/internal_iface.conf'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Enable internal iface
  ansible.builtin.file:
    src: /etc/network/iface-available.d/internal_iface.conf
    dest: /etc/network/interfaces.d/internal_iface.conf
    owner: root
    group: root
    state: link
  become: true
  when: network_setup_internal_iface
