---
- name: Get full hostname
  ansible.builtin.command: hostname --long
  changed_when: false
  register: network_hostname_long_stats
  failed_when: |
    network_hostname_long_stats.rc != 0
      and network_hostname_long_stats.stdout == network_public_hostname

- name: Install netplan
  ansible.builtin.apt:
    name:
    - 'netplan.io={{ network_netplan_version }}*'
    - 'openvswitch-switch={{ network_openvswitch_version }}*'
    state: present
  become: true

- name: Install public iface
  ansible.builtin.template:
    src: etc/netplan/101_public_iface.yaml
    dest: /etc/netplan/101_public_iface.yaml
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  notify:
    - Apply netplan

- name: Install internal iface
  ansible.builtin.template:
    src: etc/netplan/102_internal_iface.yaml
    dest: /etc/netplan/102_internal_iface.yaml
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  notify:
    - Apply netplan

- name: Notify restart systemd-networkd if not started
  ansible.builtin.command: systemctl status systemd-networkd
  become: true
  register: systemd_networkd_service_status
  changed_when: systemd_networkd_service_status.rc != 0
  failed_when: false
  notify:
    - Restart systemd-networkd

- name: Notify restart ovsdb-server if not started
  ansible.builtin.command: systemctl status ovsdb-server
  become: true
  register: ovsdb_server_service_status
  changed_when: ovsdb_server_service_status.rc != 0
  failed_when: false
  notify:
    - Restart ovsdb-server
