---
- name: Check internal host variable is required
  ansible.builtin.debug:
    var: 'network_internal_hostname'

- name: Get full hostname
  ansible.builtin.command: hostname --long
  changed_when: false
  register: network_hostname_long_stats

- name: Set full hostname
  ansible.builtin.set_fact:
    network_hostname: '{{ network_hostname_long_stats.stdout }}'

- name: Directory of interfaces is available
  ansible.builtin.file:
    path: /etc/network/iface-available.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install internal iface
  ansible.builtin.template:
    src: etc/network/iface-available.d/internal_iface.conf
    dest: '/etc/network/iface-available.d/internal_iface.conf'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Enable internal iface
  ansible.builtin.file:
    src: /etc/network/iface-available.d/internal_iface.conf
    dest: /etc/network/interfaces.d/internal_iface.conf
    owner: root
    group: root
    state: link
  become: true
