package vagrant_private_ca

root_ca_certificate:
"""
-----BEGIN CERTIFICATE-----
MIIB7jCCAXUCCQDxU0uZPzcEODAKBggqhkjOPQQDBDBhMQswCQYDVQQGEwJKUDEO
MAwGA1UECAwFVG9reW8xCjAIBgNVBAcMAS4xEDAOBgNVBAoMB1ByaXZhdGUxCjAI
BgNVBAsMAS4xGDAWBgNVBAMMD1ByaXZhdGUgUm9vdCBDQTAeFw0yMzA0MDEwNjE1
NDhaFw0zMzAzMjkwNjE1NDhaMGExCzAJBgNVBAYTAkpQMQ4wDAYDVQQIDAVUb2t5
bzEKMAgGA1UEBwwBLjEQMA4GA1UECgwHUHJpdmF0ZTEKMAgGA1UECwwBLjEYMBYG
A1UEAwwPUHJpdmF0ZSBSb290IENBMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEuCnm
v/MFTtBHM18G1W32kY1qGwy8y1Zeas49tqWh3qPQZdSLHW6iLom+9vIoutVzaJRy
/YT2A+0Weh3un8cTFKO2TyYLByAmtJr2iVPn+9CiFdi4idnVf2+obDlwa7iwMAoG
CCqGSM49BAMEA2cAMGQCMEMm2FN3mPUiInrOXAJTVEzgcojmQrhBJIOXwsThyVmh
ehCnvR0ilAGdBKiNRcNfAAIwII5/q172256j/YrVNmaT/fdCYnn6qM0bQECJ/LWT
BdYh85/JZW1MunRyYzHZpcNA
-----END CERTIFICATE-----
"""
root_ca_crl:
  """
  -----BEGIN X509 CRL-----
  MIIBGTCBoAIBATAKBggqhkjOPQQDBDBhMQswCQYDVQQGEwJKUDEOMAwGA1UECAwF
  VG9reW8xCjAIBgNVBAcMAS4xEDAOBgNVBAoMB1ByaXZhdGUxCjAIBgNVBAsMAS4x
  GDAWBgNVBAMMD1ByaXZhdGUgUm9vdCBDQRcNMjMwNDAxMDYxNTUxWhcNMjMwNTAx
  MDYxNTUxWqAOMAwwCgYDVR0UBAMCAQEwCgYIKoZIzj0EAwQDaAAwZQIxAKk7iXz3
  7edcGudaOFhcw32Hu7ZsmCiwiuLADZSWjen++f2AU2e5exJi1y4i6pD5yAIwZ/nU
  7q/J7K56I7t2RcXYIi9bfMqzsbhdiEJCfgqSWptcPEiyjGq1FO2N7mm4vDR8
  -----END X509 CRL-----
  """
root_ca_database:
  """
  V	280330061600Z		01	unknown	/C=JP/ST=Tokyo/L=./O=Private/OU=./CN=Private TLS CA
  """
root_ca_privkey:
  "__ansible_vault":
    """
    """

inter_tls_ca_certificate:
  """
  -----BEGIN CERTIFICATE-----
  MIIDVjCCAtugAwIBAgIBATAKBggqhkjOPQQDBDBhMQswCQYDVQQGEwJKUDEOMAwG
  A1UECAwFVG9reW8xCjAIBgNVBAcMAS4xEDAOBgNVBAoMB1ByaXZhdGUxCjAIBgNV
  BAsMAS4xGDAWBgNVBAMMD1ByaXZhdGUgUm9vdCBDQTAeFw0yMzA0MDEwNjE2MDBa
  Fw0yODAzMzAwNjE2MDBaMGAxCzAJBgNVBAYTAkpQMQ4wDAYDVQQIDAVUb2t5bzEK
  MAgGA1UEBwwBLjEQMA4GA1UECgwHUHJpdmF0ZTEKMAgGA1UECwwBLjEXMBUGA1UE
  AwwOUHJpdmF0ZSBUTFMgQ0EwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQty7P5w0MH
  ZftFTdWLCg/G+qhCgemaXR+Gbh6Ulv5CveeOaK39juLljnweMJqpBlSlW3jAwh2Z
  wtFkQKAy3E+1uju+oIqMwES7Wory26lgshurXzZTCIMN+mBXAaPrInqjggFmMIIB
  YjAdBgNVHQ4EFgQUAWdVO/PFWEErsdhsR8jMwbwmo2cwewYDVR0jBHQwcqFlpGMw
  YTELMAkGA1UEBhMCSlAxDjAMBgNVBAgMBVRva3lvMQowCAYDVQQHDAEuMRAwDgYD
  VQQKDAdQcml2YXRlMQowCAYDVQQLDAEuMRgwFgYDVQQDDA9Qcml2YXRlIFJvb3Qg
  Q0GCCQDxU0uZPzcEODBFBggrBgEFBQcBAQQ5MDcwNQYIKwYBBQUHMAKGKWh0dHA6
  Ly9jYS1sb2NhbC5taXp1bmFzaGkud29yay9yb290Q0EuY3J0MDoGA1UdHwQzMDEw
  L6AtoCuGKWh0dHA6Ly9jYS1sb2NhbC5taXp1bmFzaGkud29yay9yb290Q0EuY3Js
  MBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQG
  CCsGAQUFBwMBBggrBgEFBQcDAjAKBggqhkjOPQQDBANpADBmAjEA0ML5FB2obPMq
  kqyBSb8aCC4+p/jCecuMPqucQ8Ot7dmbsS7cTCatcL7GT97AYagyAjEAq/XiU3sv
  7E9F9BTu3D2iw4JaNSD+G8XhUlfV3vevcvioPTmFo01apDWupPi+zUUk
  -----END CERTIFICATE-----
  """
inter_tls_ca_crl:
  """
  -----BEGIN X509 CRL-----
  MIIBFzCBnwIBATAKBggqhkjOPQQDBDBgMQswCQYDVQQGEwJKUDEOMAwGA1UECAwF
  VG9reW8xCjAIBgNVBAcMAS4xEDAOBgNVBAoMB1ByaXZhdGUxCjAIBgNVBAsMAS4x
  FzAVBgNVBAMMDlByaXZhdGUgVExTIENBFw0yMzA0MDEwNjE2MDJaFw0yMzA1MDEw
  NjE2MDJaoA4wDDAKBgNVHRQEAwIBATAKBggqhkjOPQQDBANnADBkAjBE3yg1hEvU
  dE4oZJmul52gscX/mUFj/4hhBxz78Mfak7OShDqXfwSyX+gSc+zcOC0CMF05a/Y6
  Zrn6GScQ9sq6t+PAxLKBxz47WGNBIHQdpgeF9qzgGsJnZq8c+N6Ku+xwjw==
  -----END X509 CRL-----
  """
inter_tls_ca_database:
  """
  V	240331061753Z		01	unknown	/C=JP/ST=Tokyo/L=./O=Private/OU=./CN=mstdn-local.mizunashi.work
  V	240331072918Z		02	unknown	/C=JP/ST=Tokyo/L=./O=Private/OU=./CN=*.mizunashi.private
  """
inter_tls_ca_privkey:
  "__ansible_vault":
    """
    """
