apiVersion: 1

groups:
  - orgId: 1
    name: 'FluentBit Stats: Instantly'
    folder: Alert
    interval: 1m

    rules:
      - uid: 'alert_FluentBitStats_ErrorsTooMany'
        title: 'FluentBit Stats: Errors Too Many'
        condition: errors_total_last_gt_threshold
        for: 5m
        isPaused: false
        noDataState: NoData
        execErrState: Error

        annotations:
          __dashboardUid__: dashboard_FluentBitStats
          __panelId__: "11"
          summary: 'fluent-bit on the instance {{ "{{ $labels.instance }}" }} raise many errors to output.'
        labels:
          severity: error

        data:
          - refId: errors_total
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ds_prometheus
            model:
              refId: errors_total
              expr: rate(fluentbit_output_errors_total [1m])
              editorMode: code
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
          - refId: errors_total_last
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: errors_total_last
              type: reduce
              datasource:
                type: __expr__
                uid: __expr__
              expression: errors_total
              reducer: last
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - errors_total_last
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: errors_total_last_gt_threshold
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: errors_total_last_gt_threshold
              type: threshold
              datasource:
                type: __expr__
                uid: __expr__
              expression: errors_total_last
              conditions:
                - evaluator:
                    params:
                        - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - errors_total_last_gt_threshold
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200

      - uid: 'alert_FluentBitStats_RetriesFailsTooMany'
        title: 'FluentBit Stats: Retries Failed Too Many'
        condition: retries_failed_total
        for: 5m
        isPaused: false
        noDataState: NoData
        execErrState: Error

        annotations:
          __dashboardUid__: dashboard_FluentBitStats
          __panelId__: "11"
          summary: 'fluent-bit on the instance {{ "{{ $labels.instance }}" }} failed to retry to output.'
        labels:
          severity: error

        data:
          - refId: retries_failed_total
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ds_prometheus
            model:
              refId: retries_failed_total
              expr: rate(fluentbit_output_retries_failed_total [1m])
              editorMode: code
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
          - refId: retries_failed_total_last
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: retries_failed_total_last
              type: reduce
              datasource:
                type: __expr__
                uid: __expr__
              expression: retries_failed_total
              reducer: last
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - retries_failed_total_last
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: retries_failed_total_last_gt_threshold
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: retries_failed_total_last_gt_threshold
              type: threshold
              datasource:
                type: __expr__
                uid: __expr__
              expression: retries_failed_total_last
              conditions:
                - evaluator:
                    params:
                        - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - retries_failed_total_last_gt_threshold
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
