apiVersion: 1

groups:
  - orgId: 1
    name: 'Nginx Exporter: Instantly'
    folder: Alert
    interval: 1m

    rules:
      - uid: 'alert_NginxExporter_NginxDown'
        title: 'Nginx Exporter: Nginx Down'
        condition: C
        for: 2m
        isPaused: false
        noDataState: NoData
        execErrState: Error

        annotations:
          __dashboardUid__: dashboard_NginxExporter
          __panelId__: "2"
          summary: 'Nginx on the instance {{ "{{ $labels.instance }}" }} is down'
        labels:
          severity: error

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ds_prometheus
            model:
              refId: A
              expr: nginx_up
              editorMode: code
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - B
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params:
                        - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                        - C
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
