apiVersion: 1

groups:
  - orgId: 1
    name: 'Prometheus: Instantly'
    folder: Alert
    interval: 1m

    rules:
      - uid: 'alert_prometheus_ExporterDown'
        title: 'Prometheus: Exporter Down'
        condition: C
        for: 5m
        isPaused: false
        noDataState: NoData
        execErrState: Error

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ds_prometheus
            model:
              refId: A
              expr: up
              editorMode: code
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - B
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params:
                        - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                        - C
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
