apiVersion: 1

groups:
  - orgId: 1
    name: 'StatsD Exporter - Mastodon: Instantly'
    folder: Alert
    interval: 1m

    rules:
      - uid: 'alert_StatsdExporterMastodon_SidekiqDown'
        title: 'Statsd Exporter - Mastodon: Sidekiq Down'
        condition: C
        for: 2m
        isPaused: false
        noDataState: NoData
        execErrState: Error

        annotations:
          __dashboardUid__: dashboard_StatsdExporterMastodon
          __panelId__: "48"
          summary: 'Mastodon sidekiq on the instance {{ "{{ $labels.instance }}" }} is down'
        labels:
          severity: error

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ds_prometheus
            model:
              refId: A
              expr: mastodon_sidekiq_processes_size
              editorMode: code
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - B
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params:
                        - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                        - C
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200

      - uid: 'alert_StatsdExporterMastodon_EnqueuedJobsTooMany'
        title: 'Statsd Exporter - Mastodon: Enqueued jobs are too many'
        condition: C
        for: 2m
        isPaused: false
        noDataState: NoData
        execErrState: Error

        annotations:
          __dashboardUid__: dashboard_StatsdExporterMastodon
          __panelId__: "48"
          summary: 'Enqueued jobs of Mastodon on the instance {{ "{{ $labels.instance }}" }} are too many.'
        labels:
          severity: error

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ds_prometheus
            model:
              refId: A
              expr: increase(mastodon_sidekiq_enqueued [1m]) / (increase(mastodon_sidekiq_processed [1m]) + 1)
              editorMode: code
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: B
              type: reduce
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - B
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              refId: C
              type: threshold
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              conditions:
                - evaluator:
                    params:
                        - 2
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                        - C
                  reducer:
                    params: []
                    type: last
                  type: query
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
