#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

CA_DIR="$(cd "$(dirname "$0")" && pwd)"

INTER_TLS_CA_DIR="$CA_DIR/interCA_TLS"

function show_usage() {
  cat <<EOS
Usage: $0 --dist-dir PATH [option...]

Options:
  --extra-ext key=value : Extra extensions (may be repeated)
EOS
}

REQ_EXTRA_EXTS=()
while [ "$#" -ne 0 ]; do
  case "$1" in
    '--dist-dir' )
      DIST_DIR="$2"
      shift
      ;;
    '--extra-ext' )
      REQ_EXTRA_EXTS+=(-addext "$2")
      shift
      ;;
    '-?' | '--help' )
      show_usage
      exit
      ;;
    * )
      echo "Unknown option: $1" 1>&2
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "${DIST_DIR:-}" ]; then
  echo "Not enough arguments." 1>&2
  show_usage
  exit 1
fi

mkdir -p "$DIST_DIR"
DIST_DIR="$(cd "$DIST_DIR" && pwd)"

OUT_CSR="$DIST_DIR/cert.csr"
OUT_CERT="$DIST_DIR/cert.pem"
OUT_FULLCHAIN="$DIST_DIR/fullchain.pem"
OUT_CHAIN="$DIST_DIR/chain.pem"
OUT_KEY="$DIST_DIR/privkey.pem"

REQ_ARGS=(
  -config "$CA_DIR/req.cnf"
  -newkey EC
  -pkeyopt ec_paramgen_curve:secp384r1
  -pkeyopt ec_param_enc:named_curve
  -nodes
  -out "$OUT_CSR"
  -keyout "$OUT_KEY"
)

REQ_ARGS+=("${REQ_EXTRA_EXTS[@]}")

openssl req "${REQ_ARGS[@]}"

cd "$CA_DIR" && openssl ca \
  -config "$INTER_TLS_CA_DIR/ca.cnf" \
  -notext \
  -batch \
  -in "$OUT_CSR" \
  -out "$OUT_CERT"

cp "$INTER_TLS_CA_DIR/cacert.pem" "$OUT_CHAIN"

cat "$OUT_CERT" "$OUT_CHAIN" > "$OUT_FULLCHAIN"
