#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

CA_DIR="$(cd "$(dirname "$0")" && pwd)"

PACKAGE_NAME="${PACKAGE_NAME:-"$(basename "$CA_DIR")"}"

cat <<EOS >"$CA_DIR/vars.cue"
package ${PACKAGE_NAME}

root_ca_certificate:
"""
$(cat "$CA_DIR/rootCA/cacert.pem")
"""
root_ca_crl:
"""
$(cat "$CA_DIR/rootCA/crl.pem")
"""
root_ca_database:
"""
$(cat "$CA_DIR/rootCA/var/index.txt")
"""
root_ca_privkey: "__ansible_vault":
"""
$(cat "$CA_DIR/rootCA/private/cakey.pem.vaulted")
"""

inter_tls_ca_certificate:
"""
$(cat "$CA_DIR/interCA_TLS/cacert.pem")
"""
inter_tls_ca_crl:
"""
$(cat "$CA_DIR/interCA_TLS/crl.pem")
"""
inter_tls_ca_database:
"""
$(cat "$CA_DIR/interCA_TLS/var/index.txt")
"""
inter_tls_ca_privkey: "__ansible_vault":
"""
$(cat "$CA_DIR/interCA_TLS/private/cakey.pem.vaulted")
"""
EOS
