---
- name: Install certbot
  ansible.builtin.apt:
    name: 'certbot={{ certbot_version }}*'
    state: present
  become: true

- name: Directory of certbot is available
  ansible.builtin.file:
    path: '{{ certbot_webroot_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
