---
- name: Install certbot
  ansible.builtin.apt:
    name: 'certbot={{ certbot_version }}*'
    state: present
  become: true

- name: Disabled builtin renewal timer
  ansible.builtin.systemd:
    name: certbot.timer
    state: stopped
    enabled: false
    masked: true
  become: true

- name: Disabled builtin renewal
  ansible.builtin.systemd:
    name: certbot
    state: stopped
    enabled: false
    masked: true
  become: true

- name: Directory of certbot webroot is available
  ansible.builtin.file:
    path: '{{ certbot_webroot_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Copy letsencrypt config
  ansible.builtin.template:
    src: etc/letsencrypt/cli.ini
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install cerbot renew
  ansible.builtin.copy:
    src: usr/local/bin/certbot-renew
    dest: /usr/local/bin/certbot-renew
    owner: root
    group: root
    mode: '0755'
    backup: true
    validate: bash -n %s
  become: true
