package network_host_vars

network_hostname: string

network_public_ipv4_address: string
network_public_ipv4_gateway: string
network_public_ipv4_netmask: string
network_public_ipv4_nameserver: string
network_public_ipv4_search: string

network_public_ipv6_address: string
network_public_ipv6_gateway?: string
network_public_ipv6_netmask: string

network_internal_hostname: string
network_internal_ipv4_address: string
