---
- name: Copy gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/firefish-dist-pkg.gpg
    dest: /usr/share/keyrings/firefish-dist-pkg.gpg
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install firefish repository
  ansible.builtin.template:
    src: etc/apt/sources.list.d/firefish-dist-pkg.list
    dest: /etc/apt/sources.list.d/firefish-dist-pkg.list
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  register: firefish_install_repository_result

- name: Install firefish
  ansible.builtin.apt:
    name: 'firefish={{ firefish_version }}*'
    state: present
    update_cache: '{{ firefish_install_repository_result.changed }}'
  become: true

- name: Copy config of firefish
  ansible.builtin.template:
    src: etc/firefish/config.yml
    dest: /etc/firefish/config.yml
    owner: firefish
    group: firefish
    mode: '0640'
    backup: true
  become: true
  notify:
    - Restart firefish

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/firefish.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override service
  ansible.builtin.template:
    src: etc/systemd/system/firefish.service.d/override.conf
    dest: /etc/systemd/system/firefish.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart firefish

- name: Validate systemd service
  ansible.builtin.command: |
    /opt/bin/systemd-validate /lib/systemd/system/firefish.service
  become: true
  changed_when: false
  register: firefish_systemd_validate_result
  failed_when: |
    firefish_systemd_validate_result.rc != 0
    or firefish_systemd_validate_result.stderr != ''

- name: Directory of logs is available
  ansible.builtin.file:
    path: /var/log/firefish
    state: directory
    owner: firefish
    group: adm
    mode: '0755'
  become: true

- name: Backup original logrotate config
  ansible.builtin.command:
    cmd: /opt/bin/logrotate-backup firefish
  changed_when: false
  become: true

- name: Install logrotate config
  ansible.builtin.template:
    src: etc/logrotate-available.d/firefish
    dest: /etc/logrotate-available.d/firefish
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/logrotate-validate %s
  become: true

- name: Enable logrotate config
  ansible.builtin.file:
    src: /etc/logrotate-available.d/firefish
    dest: /etc/logrotate.d/firefish
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Notify restart firefish if not started
  ansible.builtin.command: systemctl status firefish
  become: true
  register: firefish_service_status
  changed_when: firefish_service_status.rc != 0
  failed_when: false
  notify:
    - Restart firefish
