---
firefish_version: '1.0.4'
firefish_deb_url: https://github.com/mizunashi-mana/firefish-dist-pkg/releases/download/v1.0.4%2Bbeta31-d2023092200-release/debian-bookworm_firefish_1.0.4+beta31-d2023092200-release_amd64.deb
