---
- name: Install node exporter
  ansible.builtin.apt:
    name: 'prometheus-node-exporter={{ node_exporter_version }}*'
    state: present
  become: true

- name: Notify restart node exporter if not started
  ansible.builtin.command: systemctl status prometheus-node-exporter
  become: true
  register: node_exporter_service_status
  changed_when: node_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart node-exporter
