---
- name: Install node exporter
  ansible.builtin.apt:
    name: 'prometheus-node-exporter={{ node_exporter_version }}*'
    state: present
  become: true

- name: Copy node exporter environment
  ansible.builtin.template:
    src: etc/default/prometheus-node-exporter
    dest: /etc/default/prometheus-node-exporter
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart node-exporter

- name: Install node exporter custom collector
  ansible.builtin.template:
    src: usr/local/bin/node_exporter_custom_collector
    dest: /usr/local/bin/node_exporter_custom_collector
    owner: root
    group: root
    mode: '0755'
    backup: true
    validate: bash -n %s
  become: true

- name: Directory of node exporter custom collector is available
  ansible.builtin.file:
    path: '{{ node_exporter_custom_collector_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install node exporter service
  ansible.builtin.template:
    src: usr/lib/systemd/system/prometheus-node-exporter.service
    dest: /usr/lib/systemd/system/prometheus-node-exporter.service
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  notify:
    - Restart node-exporter

- name: Notify restart node exporter if not started
  ansible.builtin.command: systemctl status prometheus-node-exporter
  become: true
  register: node_exporter_service_status
  changed_when: node_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart node-exporter
