---
- name: Install logrotate config
  ansible.builtin.template:
    src: etc/logrotate-available.d/rsyslog
    dest: /etc/logrotate-available.d/rsyslog
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/logrotate-validate %s
  become: true

- name: Enable logrotate config
  ansible.builtin.file:
    src: /etc/logrotate-available.d/rsyslog
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Notify restart syslog if not started
  ansible.builtin.command: systemctl status rsyslog
  become: true
  register: syslog_service_status
  changed_when: syslog_service_status.rc != 0
  failed_when: false
  notify:
    - Restart syslog
