---
- name: Reload dnsmasq
  ansible.builtin.set_fact:
    dnsmasq_handler_state: reloaded
  become: true
  listen: Reload dnsmasq

- name: Restart dnsmasq
  ansible.builtin.set_fact:
    dnsmasq_handler_state: restarted
  become: true
  listen: Restart dnsmasq

- name: Restart or reload dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: '{{ dnsmasq_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart dnsmasq
  - Reload dnsmasq

- name: Check systemd service
  ansible.builtin.command: systemctl status dnsmasq
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ dnsmasq_listen_port }}'
    state: started
    timeout: 60
  listen: Check
