---
- name: Directory of PKI is available
  ansible.builtin.file:
    path: /etc/pki
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of private CA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of private RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of CRL of private RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA/crl
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of certs of private RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA/certs
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of keys of private RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA/private
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: true

- name: Directory of data of private RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA/var
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Serial file of RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA/var/serial
    state: file
    owner: root
    group: root
    mode: '0644'
  register: private_ca_rca_serial_stats
  failed_when: false
  become: true

- name: Initialize RCA serial number if needed
  ansible.builtin.copy:
    content: '01'
    dest: /etc/pki/private-local-ca/rootCA/var/serial
    owner: root
    group: root
    mode: '0600'
  become: true
  when: private_ca_rca_serial_stats.state != 'file'

- name: CRL number file of RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA/var/crlnumber
    state: file
    owner: root
    group: root
    mode: '0600'
  register: private_ca_rca_crlnumber_stats
  failed_when: false
  become: true

- name: Initialize RCA serial number if needed
  ansible.builtin.copy:
    content: '01'
    dest: /etc/pki/private-local-ca/rootCA/var/crlnumber
    owner: root
    group: root
    mode: '0644'
  become: true
  when: private_ca_rca_crlnumber_stats.state != 'file'

- name: Index file of RCA is available
  ansible.builtin.file:
    path: /etc/pki/private-local-ca/rootCA/var/index.txt
    state: file
    owner: root
    group: root
    mode: '0644'
  register: private_ca_rca_index_stats
  failed_when: false
  become: true

- name: Initialize RCA index if needed
  ansible.builtin.copy:
    content: ''
    dest: /etc/pki/private-local-ca/rootCA/var/index.txt
    owner: root
    group: root
    mode: '0644'
  become: true
  when: private_ca_rca_index_stats.state != 'file'

- name: Copy CA cert request config
  ansible.builtin.template:
    src: etc/pki/private-local-ca/rootCA/cacert-req.cnf
    dest: /etc/pki/private-local-ca/rootCA/cacert-req.cnf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create CA certificate
  ansible.builtin.command:
    cmd: |
      openssl req \
        -config /etc/pki/private-local-ca/rootCA/cacert-req.cnf \
        -x509 \
        -nodes \
        -newkey EC \
        -pkeyopt ec_paramgen_curve:prime256v1 \
        -passout {{ private_ca_root_key_password }} \
        -days 3650 \
        -out /etc/pki/private-local-ca/rootCA/cacert.pem \
        -keyout /etc/pki/private-local-ca/rootCA/private/cakey.pem
    creates: /etc/pki/private-local-ca/rootCA/cacert.pem
  become: true
  no_log: true

- name: Copy CA config
  ansible.builtin.template:
    src: etc/pki/private-local-ca/rootCA/ca.cnf
    dest: /etc/pki/private-local-ca/rootCA/ca.cnf
    owner: root
    group: root
    mode: '0644'
  become: true
