---
- name: Restart exim
  ansible.builtin.systemd:
    name: exim4
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart exim

- name: Check systemd service
  ansible.builtin.command: systemctl status exim4
  become: true
  changed_when: false
  listen: Check
