---
- name: Install ACME certificate
  ansible.builtin.command:
    cmd: |
      certbot certonly
        --server '{{ certbot_install_acme_cert_server }}'
        --webroot --webroot-path '{{ certbot_webroot_dir }}'
        --domain '{{ certbot_install_acme_cert_domain }}'
        --email '{{ certbot_acme_notification_email }}'
        --agree-tos
        --no-eff-email
    creates: '/etc/letsencrypt/live/{{ certbot_install_acme_cert_domain }}/fullchain.pem'
    stdin: ''
  environment:
    REQUESTS_CA_BUNDLE: '{{ certbot_install_acme_cert_ca_bundle }}'
  become: true

- name: Install environment
  ansible.builtin.template:
    src: 'etc/default/certbot_renew_xxx'
    dest: '/etc/default/certbot_renew_{{ certbot_install_acme_cert_domain }}'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install service
  ansible.builtin.template:
    src: 'etc/systemd/system/certbot_renew_xxx.service'
    dest: '/etc/systemd/system/certbot_renew_{{ certbot_install_acme_cert_domain }}.service'
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  register: certbot_install_acme_cert_service_result

- name: Install timer
  ansible.builtin.template:
    src: 'etc/systemd/system/certbot_renew_xxx.timer'
    dest: '/etc/systemd/system/certbot_renew_{{ certbot_install_acme_cert_domain }}.timer'
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  register: certbot_install_acme_cert_timer_result

- name: Reload service
  ansible.builtin.systemd:
    name: 'certbot_renew_{{ certbot_install_acme_cert_domain }}.service'
    enabled: true
    daemon_reload: true
  become: true
  when: certbot_install_acme_cert_service_result.changed

- name: Reload timer
  ansible.builtin.systemd:
    name: 'certbot_renew_{{ certbot_install_acme_cert_domain }}.timer'
    state: started
    enabled: true
    daemon_reload: true
  become: true
  when: certbot_install_acme_cert_timer_result.changed
