---
- name: Install http redirector site
  ansible.builtin.template:
    src: etc/nginx/sites-available/http_default.conf
    dest: /etc/nginx/sites-available/http_default.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Enable http redirector site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/http_default.conf
    dest: /etc/nginx/sites-enabled/http_default.conf
    owner: root
    group: root
    state: link
  become: true
  notify:
    - Reload nginx
