---
- name: Install site
  ansible.builtin.template:
    src: etc/nginx/sites-available/http_redirector.conf
    dest: /etc/nginx/sites-available/http_redirector.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/nginx-site-validate %s
  become: true
  notify:
    - Reload nginx

- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/http_redirector.conf
    dest: /etc/nginx/sites-enabled/http_redirector.conf
    owner: root
    group: root
    state: link
  become: true
  notify:
    - Restart nginx
