package nginx_site_minio_server

nginx_site_minio_server_domain: string

nginx_site_minio_server_acme_challenge_url: string
nginx_site_minio_server_ca_bundle_path: string

nginx_site_minio_server_listen_port: uint | *6210
