---
- name: The workuser is available
  ansible.builtin.user:
    name: '{{ workuser_setup_username }}'
    home: '{{ workuser_setup_home_directory }}'
    state: present
    groups: sudo
    append: true
  become: true

- name: The home directory is available
  ansible.builtin.file:
    path: '{{ workuser_setup_home_directory }}'
    state: directory
    owner: '{{ workuser_setup_username }}'
    group: '{{ workuser_setup_username }}'
    mode: '0755'
  become: true

- name: The directory of SSH is available
  ansible.builtin.file:
    path: '{{ workuser_setup_home_directory }}/.ssh'
    state: directory
    owner: '{{ workuser_setup_username }}'
    group: '{{ workuser_setup_username }}'
    mode: '0700'
  become: true

- name: Authorized keys are available
  ansible.builtin.lineinfile:
    path: '{{ workuser_setup_home_directory }}/.ssh/authorized_keys'
    line: '{{ item.key }}'
    owner: '{{ workuser_setup_username }}'
    group: '{{ workuser_setup_username }}'
    mode: '0600'
  become: true
  loop: '{{ workuser_setup_ssh_authorized_keys|dict2items }}'
