---
- name: Install nftables
  ansible.builtin.apt:
    name: 'nftables={{ nftables_version }}*'
    state: present
  become: true

- name: Directory of nftables inbound configs is available
  ansible.builtin.file:
    path: /etc/nftables-inbound.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of nftables chain configs is available
  ansible.builtin.file:
    path: /etc/nftables-chain.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Copy nftables config
  ansible.builtin.copy:
    src: etc/nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0755'
    backup: true
    validate: nft -c -f %s
  become: true
  notify:
    - Restart nftables

- name: Copy nftables tcp accept config
  ansible.builtin.template:
    src: etc/nftables-inbound.d/accept_tcp_dports.conf
    dest: /etc/nftables-inbound.d/accept_tcp_dports.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nftables

- name: Copy nftables chain jump config
  ansible.builtin.template:
    src: etc/nftables-inbound.d/jump_saddr_chains.conf
    dest: /etc/nftables-inbound.d/jump_saddr_chains.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nftables

- name: Copy nftables restricted accept config
  ansible.builtin.template:
    src: etc/nftables-chain.d/accept_tcp_dports.conf
    dest: /etc/nftables-chain.d/accept_tcp_dports.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nftables

- name: Notify restart nftables if not started
  ansible.builtin.command: systemctl status nftables
  become: true
  register: nftables_service_status
  changed_when: nftables_service_status.rc != 0
  failed_when: false
  notify:
    - Restart nftables
