---
- name: Install nftables
  ansible.builtin.apt:
    name: 'nftables={{ nftables_version }}*'
    state: present
  become: true

- name: Install ulogd
  ansible.builtin.apt:
    name:
    - 'ulogd2={{ nftables_ulogd_version }}*'
    - 'ulogd2-json={{ nftables_ulogd_version }}*'
    state: present
  become: true

- name: Directory of nftables inbound configs is available
  ansible.builtin.file:
    path: /etc/nftables-inbound.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Directory of nftables chain configs is available
  ansible.builtin.file:
    path: /etc/nftables-chain.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Copy nftables config
  ansible.builtin.copy:
    src: etc/nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0755'
    backup: true
    validate: nft -c -f %s
  become: true
  notify:
    - Restart nftables

- name: Copy nftables tcp accept config
  ansible.builtin.template:
    src: etc/nftables-inbound.d/accept_tcp_dports.conf
    dest: /etc/nftables-inbound.d/accept_tcp_dports.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nftables

- name: Copy nftables chain jump config
  ansible.builtin.template:
    src: etc/nftables-inbound.d/jump_chains.conf
    dest: /etc/nftables-inbound.d/jump_chains.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nftables

- name: Copy nftables restricted accept config
  ansible.builtin.template:
    src: etc/nftables-chain.d/accept_ports_with_iif.conf
    dest: /etc/nftables-chain.d/accept_ports_with_iif.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nftables

- name: Copy nftables restricted accept config
  ansible.builtin.copy:
    src: etc/ulogd.conf
    dest: /etc/ulogd.conf
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  notify:
    - Restart ulogd

- name: Install logrotate config
  ansible.builtin.template:
    src: etc/logrotate-available.d/ulogd2
    dest: /etc/logrotate-available.d/ulogd2
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/logrotate-validate %s
  become: true

- name: Enable logrotate config
  ansible.builtin.file:
    src: /etc/logrotate-available.d/ulogd2
    dest: /etc/logrotate.d/ulogd2
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Notify restart nftables if not started
  ansible.builtin.command: systemctl status nftables
  become: true
  register: nftables_service_status
  changed_when: nftables_service_status.rc != 0
  failed_when: false
  notify:
    - Restart nftables

- name: Notify restart ulogd if not started
  ansible.builtin.command: systemctl status ulogd
  become: true
  register: nftables_ulogd_service_status
  changed_when: nftables_ulogd_service_status.rc != 0
  failed_when: false
  notify:
    - Restart ulogd
