---
- name: Reload openssh server
  ansible.builtin.set_fact:
    openssh_server_handler_state: reloaded
  become: true
  listen: Reload openssh_server

- name: Restart openssh server
  ansible.builtin.set_fact:
    openssh_server_handler_state: restarted
  become: true
  listen: Restart openssh_server

- name: Notify restart or reload sshd
  ansible.builtin.systemd:
    name: ssh
    state: '{{ openssh_server_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart openssh_server
  - Reload openssh_server

- name: Check systemd service
  ansible.builtin.command: systemctl status ssh
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    host: '::1'
    port: '{{ openssh_server_listen_port }}'
    state: started
    timeout: 60
  listen: Check
