---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - libidn11-dev
      - libssl-dev
      - libpq-dev
      - libicu-dev
      - zlib1g-dev
    state: present
  become: true

- name: Add mastodon user
  ansible.builtin.user:
    name: mastodon
    system: true
    home: /var/lib/mastodon
    shell: /usr/sbin/nologin
    state: present
  become: true

- name: Directory to work Mastodon is available
  ansible.builtin.file:
    path: /var/lib/mastodon
    state: directory
    owner: mastodon
    group: mastodon
    mode: '0755'
  become: true

- name: Get stats of Mastodon source
  ansible.builtin.stat:
    path: /var/lib/mastodon/live
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: mastodon_source_stats
  become: true

- name: The git repository of Mastodon is available
  ansible.builtin.command: |
    sudo -u mastodon git clone https://github.com/mastodon/mastodon.git /var/lib/mastodon/live
  become: true
  when: not mastodon_source_stats.stat.isdir

- name: Get git reference of specified ref
  ansible.builtin.command:
    cmd: sudo -u mastodon git rev-parse '{{ mastodon_git_ref }}'
    chdir: /var/lib/mastodon/live
  become: true
  register: mastodon_git_ref_rev_result

- name: Get git reference
  ansible.builtin.command:
    cmd: sudo -u mastodon git rev-parse HEAD
    chdir: /var/lib/mastodon/live
  become: true
  register: mastodon_git_head_rev_result

- name: Checkout specified ref
  ansible.builtin.command:
    cmd: sudo -u mastodon git checkout '{{ mastodon_git_ref }}'
    chdir: /var/lib/mastodon/live
  become: true
  when: mastodon_git_ref_rev_result.stdout != mastodon_git_head_rev_result.stdout

- name: Directory to work bundler is available
  ansible.builtin.file:
    path: /var/lib/mastodon/live/.bundle
    state: directory
    owner: mastodon
    group: mastodon
    mode: '0755'
  become: true

- name: Copy config of bundler
  ansible.builtin.template:
    src: var/lib/mastodon/live/.bundle/config
    dest: /var/lib/mastodon/live/.bundle/config
    owner: mastodon
    group: mastodon
    mode: '0644'
    backup: true
  become: true

- name: Copy config of application
  ansible.builtin.template:
    src: var/lib/mastodon/live/.env.production
    dest: /var/lib/mastodon/live/.env.production
    owner: mastodon
    group: mastodon
    mode: '0644'
    backup: true
  become: true
  diff: false

- name: Copy config of mastodon-sidekiq
  ansible.builtin.template:
    src: etc/default/mastodon-sidekiq
    dest: /etc/default/mastodon-sidekiq
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart mastodon-sidekiq

- name: Copy config of mastodon-web
  ansible.builtin.template:
    src: etc/default/mastodon-web
    dest: /etc/default/mastodon-web
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart mastodon-web

- name: Copy config of mastodon-streaming
  ansible.builtin.template:
    src: etc/default/mastodon-streaming
    dest: /etc/default/mastodon-streaming
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart mastodon-streaming

- name: Install mastodon-sidekiq service
  ansible.builtin.template:
    src: etc/systemd/system/mastodon-sidekiq.service
    dest: /etc/systemd/system/mastodon-sidekiq.service
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart mastodon-sidekiq

- name: Install mastodon-web service
  ansible.builtin.template:
    src: etc/systemd/system/mastodon-web.service
    dest: /etc/systemd/system/mastodon-web.service
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart mastodon-web

- name: Install mastodon-streaming service
  ansible.builtin.template:
    src: etc/systemd/system/mastodon-streaming.service
    dest: /etc/systemd/system/mastodon-streaming.service
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart mastodon-streaming
