#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

function show_usage() {
  cat <<EOS
Usage: $0 [option...]

Options:
  --server URI : ACME server
  --domain NAME : Domain
  --ca-bundle-path PATH : CA bundle path
EOS
}

while [ "$#" -ne 0 ]; do
  case "$1" in
    '--server' )
      SERVER="$2"
      shift
      ;;
    '--domain' )
      DOMAIN="$2"
      shift
      ;;
    '--ca-bundle-path' )
      export REQUESTS_CA_BUNDLE="$2"
      shift
      ;;
    '--help' | '-?' )
      show_usage
      exit
      ;;
    * )
      echo "Unknown option: $1"
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "$SERVER" ] || [ -z "$DOMAIN" ]; then
  echo "Not enough arguments."
  show_usage
  exit 1
fi

source /etc/certbot/install_acme_cert_config.sh

echo | certbot certonly \
  --server "$SERVER" \
  --webroot --webroot-path "$WEBROOT" \
  --domain "$DOMAIN" \
  --email "$NOTIFICATION_EMAIL" \
  --agree-tos \
  --no-eff-email

CRON_FILE="${CRON_DIR}/0certbot-renew-${DOMAIN}"
cat <<EOS > "$CRON_FILE"
set -euxo

if [ -n '$REQUESTS_CA_BUNDLE' ]; then
  export REQUESTS_CA_BUNDLE=$REQUESTS_CA_BUNDLE
fi

echo | certbot renew --cert-name '$DOMAIN'
EOS
chmod +x "$CRON_FILE"
