---
- name: Install fail2ban
  ansible.builtin.apt:
    name: 'fail2ban={{ fail2ban_version }}*'
    state: present
  become: true

- name: Backup original logrotate config
  ansible.builtin.command:
    cmd: /opt/bin/logrotate-backup fail2ban
  changed_when: false
  become: true

- name: Install logrotate config
  ansible.builtin.template:
    src: etc/logrotate-available.d/fail2ban
    dest: /etc/logrotate-available.d/fail2ban
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/logrotate-validate %s
  become: true

- name: Enable logrotate config
  ansible.builtin.file:
    src: /etc/logrotate-available.d/fail2ban
    dest: /etc/logrotate.d/fail2ban
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Copy fail2ban config for SSHd
  ansible.builtin.template:
    src: etc/fail2ban/jail.d/sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload fail2ban

- name: Notify restart fail2ban if not started
  ansible.builtin.command: systemctl status fail2ban
  become: true
  register: fail2ban_service_status
  changed_when: fail2ban_service_status.rc != 0
  failed_when: false
  notify:
    - Restart fail2ban
