---
- name: Copy fluent-bit gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/fluentbit-keyring.gpg
    dest: /usr/share/keyrings/fluentbit-keyring.gpg
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install fluent-bit repository
  ansible.builtin.template:
    src: etc/apt/sources.list.d/fluent-bit.list
    dest: /etc/apt/sources.list.d/fluent-bit.list
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  register: fluent_bit_install_repository_result

- name: Install fluent-bit
  ansible.builtin.apt:
    name: 'fluent-bit={{ fluent_bit_version }}*'
    state: present
    update_cache: '{{ fluent_bit_install_repository_result.changed }}'
  become: true

- name: Notify restart fluent-bit if not started
  ansible.builtin.command: systemctl status fluent-bit
  become: true
  register: fluent_bit_service_status
  changed_when: fluent_bit_service_status.rc != 0
  failed_when: false
  notify:
    - Restart fluent-bit
