---
- name: Copy fluent-bit gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/fluentbit-keyring.gpg
    dest: /usr/share/keyrings/fluentbit-keyring.gpg
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Install fluent-bit repository
  ansible.builtin.template:
    src: etc/apt/sources.list.d/fluent-bit.list
    dest: /etc/apt/sources.list.d/fluent-bit.list
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  register: fluent_bit_install_repository_result

- name: Install fluent-bit
  ansible.builtin.apt:
    name: 'fluent-bit={{ fluent_bit_version }}*'
    state: present
    update_cache: '{{ fluent_bit_install_repository_result.changed }}'
  become: true

- name: Install fluent-bit validator
  ansible.builtin.copy:
    src: opt/bin/fluent-bit-validate
    dest: /opt/bin/fluent-bit-validate
    owner: root
    group: root
    mode: '0755'
    backup: true
  become: true

- name: Directory of input configs is available
  ansible.builtin.file:
    path: /etc/fluent-bit/input-conf.d
    state: directory
    owner: root
    group: root
    mode: '0750'
  become: true

- name: Directory of output configs is available
  ansible.builtin.file:
    path: /etc/fluent-bit/output-conf.d
    state: directory
    owner: root
    group: root
    mode: '0750'
  become: true

- name: Copy parsers config
  ansible.builtin.template:
    src: etc/fluent-bit/parsers.conf
    dest: /etc/fluent-bit/parsers.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart fluent-bit

- name: Copy input empty config
  ansible.builtin.copy:
    content: ''
    dest: /etc/fluent-bit/input-conf.d/empty.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Copy output empty config
  ansible.builtin.copy:
    content: ''
    dest: /etc/fluent-bit/output-conf.d/empty.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Copy fluent-bit config
  ansible.builtin.template:
    src: etc/fluent-bit/fluent-bit.conf
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/fluent-bit-validate %s
  become: true
  notify:
    - Restart fluent-bit

- name: Notify restart fluent-bit if not started
  ansible.builtin.command: systemctl status fluent-bit
  become: true
  register: fluent_bit_service_status
  changed_when: fluent_bit_service_status.rc != 0
  failed_when: false
  notify:
    - Restart fluent-bit
