---
- name: Request nginx started
  ansible.builtin.meta: flush_handlers

- name: Install password file
  ansible.builtin.template:
    src: 'etc/nginx/cred.d/local_proxy.htpasswd'
    dest: '/etc/nginx/cred.d/local_proxy.htpasswd'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Install local proxy site
  ansible.builtin.template:
    src: 'etc/nginx/sites-available/local_proxy.conf'
    dest: '/etc/nginx/sites-available/local_proxy.conf'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload nginx

- name: Enable local proxy site
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/local_proxy.conf'
    dest: '/etc/nginx/sites-enabled/local_proxy.conf'
    owner: root
    group: root
    state: link
  become: true
  notify:
    - Reload nginx
