---
- name: Reload systemd-resolved
  ansible.builtin.set_fact:
    systemd_resolved_handler_state: reloaded
  become: true
  listen: Reload systemd-resolved

- name: Restart systemd-resolved
  ansible.builtin.set_fact:
    systemd_resolved_handler_state: restarted
  become: true
  listen: Restart systemd-resolved

- name: Restart or reload systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: '{{ systemd_resolved_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart systemd-resolved
  - Reload systemd-resolved

- name: The resolver is systemd stub resolver
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
  become: true
  listen:
  - Restart systemd-resolved
  - Reload systemd-resolved

- name: Check systemd service
  ansible.builtin.command: systemctl status systemd-resolved
  become: true
  changed_when: false
  listen: Check
