package postgresql

postgresql_listen_port: 5432

postgresql_max_connections: uint
postgresql_shared_buffers: string
postgresql_effective_cache_size: string
postgresql_maintenance_work_mem: string
postgresql_checkpoint_completion_target: number
postgresql_wal_buffers: string
postgresql_default_statistics_target: uint
postgresql_random_page_cost: number
postgresql_effective_io_concurrency: uint
postgresql_work_mem: string
postgresql_min_wal_size: string
postgresql_max_wal_size: string
