---
- name: Install prometheus
  ansible.builtin.apt:
    name: 'prometheus={{ prometheus_version }}*'
    state: present
  become: true

- name: Notify restart prometheus if not started
  ansible.builtin.command: systemctl status prometheus
  become: true
  register: prometheus_service_status
  changed_when: prometheus_service_status.rc != 0
  failed_when: false
  notify:
    - Restart prometheus
