---
- name: Install prometheus
  ansible.builtin.apt:
    name: 'prometheus={{ prometheus_version }}*'
    state: present
  become: true

- name: Copy prometheus config
  ansible.builtin.template:
    src: etc/prometheus/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload prometheus

- name: Directory of scrape configs is available
  ansible.builtin.file:
    path: /etc/prometheus/scrape-config.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install scrape configs
  ansible.builtin.copy:
    content: '{{ prometheus_scrape_configs[item] | to_yaml }}'
    dest: '/etc/prometheus/scrape-config.d/{{ item }}.yml'
    state: directory
    owner: root
    group: root
    mode: '0755'
    backup: true
  become: true
  loop: '{{ prometheus_scrape_configs|dict2items|map(attribute="key") }}'
  notify:
    - Reload prometheus

- name: Copy prometheus environment
  ansible.builtin.template:
    src: etc/default/prometheus
    dest: /etc/default/prometheus
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart prometheus

- name: Install prometheus service
  ansible.builtin.template:
    src: usr/lib/systemd/system/prometheus.service
    dest: /usr/lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart prometheus

- name: Notify restart prometheus if not started
  ansible.builtin.command: systemctl status prometheus
  become: true
  register: prometheus_service_status
  changed_when: prometheus_service_status.rc != 0
  failed_when: false
  notify:
    - Restart prometheus
