---
- name: Install prometheus
  ansible.builtin.apt:
    name: 'prometheus={{ prometheus_version }}*'
    state: present
  become: true

- name: Copy prometheus config
  ansible.builtin.template:
    src: etc/prometheus/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload prometheus

- name: Directory of TLS config is available
  ansible.builtin.file:
    path: /etc/prometheus/tls_config
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install client certificate
  ansible.builtin.copy:
    src: "{{ prometheus_client_certificate_cert }}\n"
    dest: /etc/prometheus/tls_config/client_certificate.pem
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Reload prometheus

- name: Install client certificate privkey
  ansible.builtin.copy:
    src: "{{ prometheus_client_certificate_privkey }}\n"
    dest: /etc/prometheus/tls_config/client_privkey.pem
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  no_log: true
  notify:
    - Reload prometheus

- name: Copy prometheus environment
  ansible.builtin.template:
    src: etc/default/prometheus
    dest: /etc/default/prometheus
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart prometheus

- name: Install prometheus service
  ansible.builtin.template:
    src: usr/lib/systemd/system/prometheus.service
    dest: /usr/lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart prometheus

- name: Notify restart prometheus if not started
  ansible.builtin.command: systemctl status prometheus
  become: true
  register: prometheus_service_status
  changed_when: prometheus_service_status.rc != 0
  failed_when: false
  notify:
    - Restart prometheus
