#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

PROJECT_DIR="$(cd "$(dirname "$(dirname "$0")")" && pwd)"

ROOT_CA_DAYS=3650
INTER_TLS_CA_DAYS=1825

function show_usage() {
  cat <<EOS
Usage: $0 --dist-dir DIR --dist-url URL --root-ca-ocsp-url URL --inter-tls-ca-ocsp-url URL [option...]

Options:
  --root-ca-days DAYS: Expired days of root CA
  --inter-tls-ca-days DAYS: Expired days of intermediate TLS CA
  --vault-id: Vault ID
  --package-name: Package name
EOS
}

while [ "$#" -ne 0 ]; do
  case "$1" in
    '--dist-dir' )
      DIST_DIR="$2"
      shift
      ;;
    '--dist-url' )
      DISTRIBUTION_URL="$2"
      shift
      ;;
    '--root-ca-ocsp-url' )
      ROOT_CA_OCSP_URL="$2"
      shift
      ;;
    '--inter-tls-ca-ocsp-url' )
      INTER_TLS_CA_OCSP_URL="$2"
      shift
      ;;
    '--root-ca-days' )
      ROOT_CA_DAYS="$2"
      shift
      ;;
    '--inter-tls-ca-days' )
      INTER_TLS_CA_DAYS="$2"
      shift
      ;;
    '--vault-id' )
      VAULT_ID="$2"
      shift
      ;;
    '--package-name' )
      PACKAGE_NAME="$2"
      shift
      ;;
    '-?' | '--help' )
      show_usage
      exit
      ;;
    * )
      echo "Unknown option: $1" 1>&2
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "${DIST_DIR:-}" ] \
  || [ -z "${DISTRIBUTION_URL:-}" ] \
  || [ -z "${ROOT_CA_OCSP_URL:-}" ] \
  || [ -z "${INTER_TLS_CA_OCSP_URL:-}" ]
then
  echo "Not enough arguments." 1>&2
  show_usage
  exit 1
fi

mkdir -p "$DIST_DIR"
DIST_DIR="$(cd "$DIST_DIR" && pwd)"

if [ -z "${PACKAGE_NAME:-}" ]; then
  PACKAGE_NAME="$(basename "$DIST_DIR")"
fi


ROOT_CA_DIR="$DIST_DIR/rootCA"
mkdir -p "$ROOT_CA_DIR/"{crl,var,newcerts,private}
if ! [ -e "$ROOT_CA_DIR/var/index.txt" ]; then
  touch "$ROOT_CA_DIR/var/index.txt"
fi
cp "$PROJECT_DIR/assets/private_ca/index.txt.attr" "$ROOT_CA_DIR/var/index.txt.attr"
if ! [ -e "$ROOT_CA_DIR/var/serial" ]; then
  echo '01' > "$ROOT_CA_DIR/var/serial"
fi
if ! [ -e "$ROOT_CA_DIR/var/crlnumber" ]; then
  echo '01' > "$ROOT_CA_DIR/var/crlnumber"
fi

openssl req \
  -config "$PROJECT_DIR/assets/private_ca/rootCA/cacert.cnf" \
  -x509 \
  -newkey EC \
  -pkeyopt ec_paramgen_curve:secp384r1 \
  -pkeyopt ec_param_enc:named_curve \
  -days "$ROOT_CA_DAYS" \
  -out "$ROOT_CA_DIR/cacert.pem" \
  -keyout "$ROOT_CA_DIR/private/cakey.pem"

m4 \
  "-D__DISTRIBUTION_URL__=${DISTRIBUTION_URL}" \
  "-D__ROOT_CA_OCSP_URL__=${ROOT_CA_OCSP_URL}" \
  "$PROJECT_DIR/assets/private_ca/rootCA/ca.cnf.m4" \
  >"$ROOT_CA_DIR/ca.cnf"

cd "$DIST_DIR" && openssl ca \
  -config "$ROOT_CA_DIR/ca.cnf" \
  -gencrl -out "$ROOT_CA_DIR/crl.pem"

ROOT_CA_KEY="$(openssl pkey -in "$ROOT_CA_DIR/private/cakey.pem" -passout 'pass:')"
ROOT_CA_VAULT_ARGS=(
  --output "$ROOT_CA_DIR/private/cakey.pem.vaulted"
)
if [ -n "${VAULT_ID:-}" ]; then
  ROOT_CA_VAULT_ARGS+=(
    --vault-id "$VAULT_ID@prompt"
    --encrypt-vault-id "$VAULT_ID"
  )
else
  ROOT_CA_VAULT_ARGS+=(
    --ask-vault-password
  )
fi
ansible-vault encrypt \
  "${ROOT_CA_VAULT_ARGS[@]}" \
  <(echo "$ROOT_CA_KEY")


INTER_TLS_CA_DIR="$DIST_DIR/interCA_TLS"
mkdir -p "$INTER_TLS_CA_DIR/"{crl,var,newcerts,private}
if ! [ -e "$INTER_TLS_CA_DIR/var/index.txt" ]; then
  touch "$INTER_TLS_CA_DIR/var/index.txt"
fi
cp "$PROJECT_DIR/assets/private_ca/index.txt.attr" "$INTER_TLS_CA_DIR/var/index.txt.attr"
if ! [ -e "$INTER_TLS_CA_DIR/var/serial" ]; then
  echo '01' > "$INTER_TLS_CA_DIR/var/serial"
fi
if ! [ -e "$INTER_TLS_CA_DIR/var/crlnumber" ]; then
  echo '01' > "$INTER_TLS_CA_DIR/var/crlnumber"
fi

openssl req \
  -config "$PROJECT_DIR/assets/private_ca/interCA_TLS/cacert.cnf" \
  -newkey EC \
  -pkeyopt ec_paramgen_curve:secp384r1 \
  -pkeyopt ec_param_enc:named_curve \
  -out "$INTER_TLS_CA_DIR/cacert.csr" \
  -keyout "$INTER_TLS_CA_DIR/private/cakey.pem"

cd "$DIST_DIR" && openssl ca \
  -config "$ROOT_CA_DIR/ca.cnf" \
  -notext \
  -batch \
  -in "$INTER_TLS_CA_DIR/cacert.csr" \
  -days "$INTER_TLS_CA_DAYS" \
  -out "$INTER_TLS_CA_DIR/cacert.pem"

m4 \
  "-D__DISTRIBUTION_URL__=${DISTRIBUTION_URL}" \
  "-D__INTER_TLS_CA_OCSP_URL__=${INTER_TLS_CA_OCSP_URL}" \
  "$PROJECT_DIR/assets/private_ca/interCA_TLS/ca.cnf.m4" \
  >"$INTER_TLS_CA_DIR/ca.cnf"

cd "$DIST_DIR" && openssl ca \
  -config "$INTER_TLS_CA_DIR/ca.cnf" \
  -gencrl -out "$INTER_TLS_CA_DIR/crl.pem"

INTER_TLS_CA_KEY="$(openssl pkey -in "$INTER_TLS_CA_DIR/private/cakey.pem" -passout 'pass:')"
INTER_TLS_CA_VAULT_ARGS=(
  --output "$INTER_TLS_CA_DIR/private/cakey.pem.vaulted"
)
if [ -n "${VAULT_ID:-}" ]; then
  INTER_TLS_CA_VAULT_ARGS+=(
    --vault-id "$VAULT_ID@prompt"
    --encrypt-vault-id "$VAULT_ID"
  )
else
  INTER_TLS_CA_VAULT_ARGS+=(
    --ask-vault-password
  )
fi
ansible-vault encrypt \
  "${INTER_TLS_CA_VAULT_ARGS[@]}" \
  <(echo "$INTER_TLS_CA_KEY")


cp "$PROJECT_DIR/assets/private_ca/req.cnf" "$DIST_DIR/req.cnf"

cp "$PROJECT_DIR/assets/private_ca/gen-tls-cert" "$DIST_DIR/gen-tls-cert"
chmod +x "$DIST_DIR/gen-tls-cert"

cp "$PROJECT_DIR/assets/private_ca/gen-vars" "$DIST_DIR/gen-vars"
chmod +x "$DIST_DIR/gen-vars"

env "PACKAGE_NAME=${PACKAGE_NAME}" "$DIST_DIR/gen-vars"
