#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

PROJECT_DIR="$(cd "$(dirname "$(dirname "$0")")" && pwd)"

ROOT_CA_DAYS=3650

function show_usage() {
  cat <<EOS
Usage: $0 --dist-dir DIR [option...]

Options:
  --root-ca-days DAYS: Expired days of root CA
  --vault-id: Vault ID
EOS
}

while [ "$#" -ne 0 ]; do
  case "$1" in
    '--dist-dir' )
      DIST_DIR="$2"
      shift
      ;;
    '--root-ca-days' )
      ROOT_CA_DAYS="$2"
      shift
      ;;
    '--vault-id' )
      VAULT_ID="$2"
      shift
      ;;
    '-?' | '--help' )
      show_usage
      exit
      ;;
    * )
      echo "Unknown option: $1" 1>&2
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "${DIST_DIR:-}" ]
then
  echo "Not enough arguments." 1>&2
  show_usage
  exit 1
fi

mkdir -p "$DIST_DIR"
DIST_DIR="$(cd "$DIST_DIR" && pwd)"


ROOT_CA_DIR="$DIST_DIR/rootCA"
mkdir -p "$ROOT_CA_DIR"/private

openssl req \
  -config "$PROJECT_DIR/assets/private_ca/rootCA/cacert.cnf" \
  -x509 \
  -newkey EC \
  -pkeyopt ec_paramgen_curve:secp384r1 \
  -pkeyopt ec_param_enc:named_curve \
  -days "$ROOT_CA_DAYS" \
  -out "$ROOT_CA_DIR/cacert.pem" \
  -keyout "$ROOT_CA_DIR/private/cakey.pem"

ROOT_CA_KEY="$(openssl pkey -in "$ROOT_CA_DIR/private/cakey.pem" -passout 'pass:')"
ROOT_CA_VAULT_ARGS=(
  --output "$ROOT_CA_DIR/private/cakey.pem.vaulted"
)
if [ -n "${VAULT_ID:-}" ]; then
  ROOT_CA_VAULT_ARGS+=(
    --vault-id "$VAULT_ID@prompt"
    --encrypt-vault-id "$VAULT_ID"
  )
else
  ROOT_CA_VAULT_ARGS+=(
    --ask-vault-password
  )
fi
ansible-vault encrypt \
  "${ROOT_CA_VAULT_ARGS[@]}" \
  <(echo "$ROOT_CA_KEY")


m4 \
  "$PROJECT_DIR/assets/private_ca/gen-vars.m4" \
  >"$DIST_DIR/gen-vars"
chmod +x "$DIST_DIR/gen-vars"

"$DIST_DIR/gen-vars"
