#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

PROJECT_DIR="$(cd "$(dirname "$(dirname "$0")")" && pwd)"

exec ssh \
  -i "$PROJECT_DIR/assets/vagrant_ssh_privkey" \
  "$@"
