#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

PROJECT_DIR="$(cd "$(dirname "$(dirname "$0")")" && pwd)"

LOCAL_BIND_PORT="${LOCAL_BIND_PORT:-9090}"

exec "$PROJECT_DIR/scripts/ssh" \
  -L "${LOCAL_BIND_PORT}:localhost:9090" \
  -N \
  vagrant@192.168.61.34
