---
- name: Install ACME server site
  ansible.builtin.template:
    src: etc/caddy/sites.d/acme_server.Caddyfile
    dest: /etc/caddy/sites.d/acme_server.Caddyfile
    owner: caddy
    group: caddy
    mode: '0644'
    backup: true
    validate: caddy validate --config %s
  become: true
  notify:
  - Reload caddy
