---
- name: minio is available
  ansible.builtin.apt:
    name: 'minio={{ minio_version }}'
    state: present
  become: true
  failed_when: false
  register: minio_installed_check

- name: Install minio
  ansible.builtin.apt:
    deb: '{{ minio_deb_url }}'
    state: present
  become: true
  when: |
    'msg' in minio_installed_check and minio_installed_check.msg is search('No package')

- name: minio-user is available
  ansible.builtin.user:
    name: minio-user
    system: true
    home: /var/lib/minio
    shell: /usr/sbin/nologin
    state: present
  become: true

- name: Directory to work minio is available
  ansible.builtin.file:
    path: /var/lib/minio
    state: directory
    owner: minio-user
    group: minio-user
    mode: '0755'
  become: true

- name: Directory of volumes is available
  ansible.builtin.file:
    path: /var/lib/minio/volumes
    state: directory
    owner: minio-user
    group: minio-user
    mode: '0700'
  become: true

- name: Copy config
  ansible.builtin.template:
    src: etc/default/minio
    dest: /etc/default/minio
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true
  diff: false
  notify:
    - Restart minio

- name: Copy service
  ansible.builtin.template:
    src: etc/systemd/system/minio.service
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  notify:
    - Restart minio

- name: Notify restart minio if not started
  ansible.builtin.command: systemctl status minio
  become: true
  register: minio_service_status
  changed_when: minio_service_status.rc != 0
  failed_when: false
  notify:
    - Restart minio
