---
- name: Install nginx exporter
  ansible.builtin.apt:
    name: 'prometheus-nginx-exporter={{ nginx_exporter_version }}*'
    state: present
  become: true

- name: Notify restart nginx exporter if not started
  ansible.builtin.command: systemctl status prometheus-nginx-exporter
  become: true
  register: nginx_exporter_service_status
  changed_when: nginx_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart nginx-exporter
