---
- name: Install nginx exporter
  ansible.builtin.apt:
    name: 'prometheus-nginx-exporter={{ nginx_exporter_version }}*'
    state: present
  become: true

- name: Copy nginx exporter environment
  ansible.builtin.template:
    src: etc/default/prometheus-nginx-exporter
    dest: /etc/default/prometheus-nginx-exporter
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nginx-exporter

- name: Directory to override is available
  ansible.builtin.file:
    path: /etc/systemd/system/prometheus-nginx-exporter.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override service
  ansible.builtin.template:
    src: etc/systemd/system/prometheus-nginx-exporter.service.d/override.conf
    dest: /etc/systemd/system/prometheus-nginx-exporter.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/systemd-validate %s
  become: true
  notify:
    - Restart nginx-exporter

- name: Validate systemd service
  ansible.builtin.command: |
    /opt/bin/systemd-validate /lib/systemd/system/prometheus-nginx-exporter.service
  become: true
  changed_when: false
  register: nginx_exporter_systemd_validate_result
  failed_when: |
    nginx_exporter_systemd_validate_result.rc != 0
    or nginx_exporter_systemd_validate_result.stderr != ''

- name: Notify restart nginx exporter if not started
  ansible.builtin.command: systemctl status prometheus-nginx-exporter
  become: true
  register: nginx_exporter_service_status
  changed_when: nginx_exporter_service_status.rc != 0
  failed_when: false
  notify:
    - Restart nginx-exporter
