---
- name: Restart redis-exporter
  ansible.builtin.systemd:
    name: prometheus-redis-exporter
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart redis-exporter

- name: Check systemd service
  ansible.builtin.command: systemctl status prometheus-redis-exporter
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ redis_exporter_listen_port }}'
    state: started
    timeout: 60
  listen: Check
