---
- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart grafana

- name: Check systemd service
  ansible.builtin.command: systemctl status grafana-server
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    host: '::1'
    port: '{{ grafana_listen_port }}'
    state: started
    timeout: 60
  listen: Check
