---
- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart grafana

- name: Check systemd service
  ansible.builtin.command: systemctl status grafana-server
  become: true
  listen: Check
