---
- name: Enable SYN cookies
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: true
    state: present
  become: true

- name: Install sudo
  ansible.builtin.apt:
    name: 'sudo=1:{{ base_sudo_version }}*'
    state: present
  become: true

- name: The workuser has the sudo group
  ansible.builtin.user:
    name: '{{ base_workuser_name }}'
    state: present
    groups: sudo
    append: true
  become: true
