---
- name: Enable SYN cookies
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: true
    state: present
  become: true

- name: Enable IPv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '0'
    sysctl_set: true
    state: present
  become: true

- name: Set timezone to UTC
  ansible.builtin.file:
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    owner: root
    group: root
    state: link
  become: true

- name: Hosts are available
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '{{ item[0] }} '
    line: |
      {{ item[0] }} {{ item[1]|map(attribute="key")|join(" ") }}'
    owner: root
    group: root
    mode: '0644'
  become: true
  loop: '{{ base_hosts_to_ips|dict2items|groupby("value") }}'
