---
- name: Check internal host variable is required
  ansible.builtin.debug:
    var: 'base_internal_hostname'

- name: Enable SYN cookies
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: true
    state: present
  become: true

- name: Install sudo
  ansible.builtin.apt:
    name: 'sudo={{ base_sudo_version }}*'
    state: present
  become: true

- name: Install CA certificates
  ansible.builtin.apt:
    name: 'ca-certificates={{ base_ca_certificates_version }}*'
    state: present
  become: true

- name: Bundled certificate is available
  ansible.builtin.file:
    path: '{{ base_ca_certificates_bundle_file }}'
    state: file
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Get resolv conf path
  ansible.builtin.command: readlink -f /etc/resolv.conf
  changed_when: false
  register: base_readlink_resolv_result

- name: Register internal DNS
  ansible.builtin.lineinfile:
    path: '{{ base_readlink_resolv_result.stdout }}'
    insertbefore: '^nameserver'
    firstmatch: true
    line: 'nameserver {{ base_internal_dns_ip }}'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
