---
- name: Enable SYN cookies
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: true
    state: present
  become: true

- name: Install sudo
  ansible.builtin.apt:
    name: 'sudo={{ base_sudo_version }}*'
    state: present
  become: true

- name: Hosts are available
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    search_string: '{{ item.key }} '
    line: '{{ item.key }} {{ item.value.primary_host }} {{ item.value.additional_hosts|join(" ") }}'
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  loop: '{{ base_hosts_entries|dict2items }}'
