---
- name: Copy apt sources
  ansible.builtin.template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Update cache if needed
  ansible.builtin.apt:
    update_cache: true
    # 1 day
    cache_valid_time: 86400
  become: true

- name: base-files is specified version
  ansible.builtin.apt:
    name: 'base-files={{ base_files_version }}*'
    state: present
  become: true

- name: linux-image is specified version
  ansible.builtin.apt:
    name: 'linux-image-amd64={{ base_linux_image_version }}*'
    state: present
  become: true

- name: Basic utilities are available
  ansible.builtin.apt:
    name:
    - 'man-db={{ base_mandb_version }}*'
    state: present
  become: true

- name: Timezone data is available
  ansible.builtin.apt:
    name:
    - 'tzdata={{ base_tzdata_version }}*'
    state: present
  become: true

- name: Locale data is available
  ansible.builtin.apt:
    name:
    - 'locales={{ base_locales_version }}*'
    state: present
  become: true

- name: Enable SYN cookies
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: true
    state: present
  become: true

- name: Enable IPv6 by default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '0'
    sysctl_set: true
    state: present
  become: true

- name: Enable IPv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '0'
    sysctl_set: true
    state: present
  become: true

- name: Set timezone to UTC
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    owner: root
    group: root
    state: link
  become: true

- name: Directory of optional bin is available
  ansible.builtin.file:
    path: /opt/bin
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Hosts are available
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '{{ item[0] }} '
    line: |
      {{ item[0] }} {{ item[1]|map(attribute="key")|join(" ") }}
    owner: root
    group: root
    mode: '0644'
  become: true
  loop: '{{ base_hosts_to_ips|dict2items|groupby("value") }}'
