---
- name: Enable SYN cookies
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    sysctl_set: true
    state: present
  become: true

- name: Install base dependencies
  ansible.builtin.apt:
    name:
    - 'sudo={{ base_sudo_version }}*'
    - 'ca-certificates={{ base_ca_certificates_version }}*'
    state: present
  become: true

- name: Bundled certificate is available
  ansible.builtin.file:
    path: '{{ base_ca_certificates_bundle_file }}'
    state: file
    owner: root
    group: root
    mode: '0644'
  become: true
