---
- name: Restart archivedon
  ansible.builtin.systemd:
    name: 'archivedon.service'
    enabled: true
    daemon_reload: true
    state: restarted
  become: true
  listen:
  - Restart archivedon

- name: Check systemd service
  ansible.builtin.command: systemctl status archivedon
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    host: localhost
    port: '{{ archivedon_listen_port }}'
    state: started
    timeout: 60
  listen: Check
