---
- name: Restart minio
  ansible.builtin.systemd:
    name: minio
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart minio

- name: Check systemd service
  ansible.builtin.command: systemctl status minio
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    host: '::1'
    port: '{{ minio_server_listen_port }}'
    state: started
    timeout: 60
  listen: Check
