---
- name: Restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart nftables

- name: Check systemd service
  ansible.builtin.command: systemctl status nftables
  become: true
  listen: Check
