---
- name: Reload nftables
  ansible.builtin.set_fact:
    nftables_handler_state: reloaded
  become: true
  listen: Reload nftables

- name: Restart nftables
  ansible.builtin.set_fact:
    nftables_handler_state: restarted
  become: true
  listen: Restart nftables

- name: Restart or reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: '{{ nftables_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart nftables
  - Reload nftables

- name: Restart ulogd
  ansible.builtin.systemd:
    name: ulogd
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart ulogd

- name: Check systemd service
  ansible.builtin.command: systemctl status nftables
  become: true
  changed_when: false
  listen: Check

- name: Check systemd service
  ansible.builtin.command: systemctl status ulogd
  become: true
  changed_when: false
  listen: Check
