---
- name: Reload prometheus
  ansible.builtin.set_fact:
    prometheus_handler_state: reloaded
  become: true
  listen: Reload prometheus

- name: Restart prometheus
  ansible.builtin.set_fact:
    prometheus_handler_state: restarted
  become: true
  listen: Restart prometheus

- name: Restart or reload prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: '{{ prometheus_handler_state }}'
    daemon_reload: true
    enabled: true
  become: true
  listen:
  - Restart prometheus
  - Reload prometheus

- name: Check systemd service
  ansible.builtin.command: systemctl status prometheus
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ prometheus_listen_port }}'
    state: started
  listen: Check
