---
- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart prometheus

- name: Check systemd service
  ansible.builtin.command: systemctl status prometheus
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    port: '{{ prometheus_listen_port }}'
    state: started
  listen: Check
