---
- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
  listen: Restart postgresql

- name: Check systemd service
  ansible.builtin.command: systemctl status postgresql
  become: true
  changed_when: false
  listen: Check

- name: Check listen port
  ansible.builtin.wait_for:
    host: '::1'
    port: '{{ postgresql_listen_port }}'
    state: started
    timeout: 60
  listen: Check
