---
# TODO: Use jemalloc version
- name: Install ruby
  ansible.builtin.apt:
    name:
      - 'ruby=1:{{ ruby_version }}*'
      - 'ruby-dev=1:{{ ruby_version }}*'
    state: present
  become: true

- name: Install bundler
  community.general.gem:
    name: bundler
    version: '{{ ruby_bundler_version }}'
    state: present
    bindir: /usr/local/bin
  become: true
