---
- name: Directory of resolved configs is available
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Register internal DNS
  ansible.builtin.template:
    src: etc/systemd/resolved.conf.d/internal_dns.conf
    dest: /etc/systemd/resolved.conf.d/internal_dns.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify:
  - Restart systemd-resolved

- name: Get stats of the systemd stub resolver
  ansible.builtin.stat:
    path: /run/systemd/resolve/stub-resolv.conf
    get_checksum: false
    get_attributes: false
    get_mime: false
  become: true
  register: systemd_resolved_stub_resolv_stat

- name: The resolver is systemd stub resolver
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    owner: root
    group: root
    force: true
  become: true
  when: systemd_resolved_stub_resolv_stat.stat.exists

- name: Notify restart systemd-resolved if stub resolver is not available
  ansible.builtin.debug:
    msg: 'Check /run/systemd/resolve/stub-resolv.conf'
  changed_when: not systemd_resolved_stub_resolv_stat.stat.exists
  notify:
    - Restart systemd-resolved

- name: Notify restart systemd-resolved if not started
  ansible.builtin.command: systemctl status systemd-resolved
  become: true
  register: systemd_resolved_service_status
  changed_when: systemd_resolved_service_status.rc != 0
  failed_when: false
  notify:
    - Restart systemd-resolved
