#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

CA_CONFIG_PATH='{{ private_ca_root_dir }}/interServerCA/ca.cnf'

function show_usage() {
  echo "Usage: $0 --out-cert PATH --out-key PATH"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    '--out-cert' )
      OUT_CERT="$2"
      shift
      ;;
    '--out-key' )
      OUT_KEY="$2"
      shift
      ;;
    '--help' )
      show_usage
      exit 0
      ;;
    * )
      echo "Unknown option: $1"
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "$OUT_CERT" ] || [ -z "$OUT_KEY" ]; then
  echo "Not enough arguments"
  show_usage
  exit 1
fi

exec openssl req \
  -config "$CA_CONFIG_PATH" \
  -x509 \
  -nodes \
  -newkey EC \
  -pkeyopt ec_paramgen_curve:prime256v1 \
  -out "$OUT_CERT" \
  -keyout "$OUT_KEY"
