#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

CA_CONFIG_PATH='{{ private_ca_root_dir }}/interCA_TLS/ca.cnf'

function show_usage() {
  echo "Usage: $0 --in-csr PATH --out-cert PATH"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    '--in-csr' )
      IN_CSR="$2"
      shift
      ;;
    '--out-cert' )
      OUT_CERT="$2"
      shift
      ;;
    '--help' )
      show_usage
      exit 0
      ;;
    * )
      echo "Unknown option: $1"
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "$IN_CSR" ] || [ -z "$OUT_CERT" ]; then
  echo "Not enough arguments"
  show_usage
  exit 1
fi

exec openssl ca \
  -config "$CA_CONFIG_PATH" \
  -verbose \
  -notext \
  -batch \
  -in "$IN_CSR" \
  -out "$OUT_CERT"
