#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

CA_CONFIG_PATH='{{ private_ca_root_dir }}/interCA_TLS/ca.cnf'
OUT_CRL='{{ private_ca_root_dir }}/interCA_TLS/crl.pem'

function show_usage() {
  echo "Usage: $0 --in-cert PATH"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    '--in-cert' )
      IN_CERT="$2"
      shift
      ;;
    '--help' )
      show_usage
      exit 0
      ;;
    * )
      echo "Unknown option: $1"
      show_usage
      exit 1
      ;;
  esac
  shift
done

if [ -z "$IN_CERT" ]; then
  echo "Not enough arguments"
  show_usage
  exit 1
fi

openssl ca \
  -config "$CA_CONFIG_PATH" \
  -revoke "$IN_CERT" \
  -gencrl \
  -out "$OUT_CRL"
