---
- name: Request nginx started
  ansible.builtin.meta: flush_handlers

- name: Install certificate
  ansible.builtin.include_role:
    name: certbot_install_acme_cert
  vars:
    certbot_install_acme_cert_server: '{{ nginx_site_firefish_front_acme_challenge_url }}'
    certbot_install_acme_cert_domain: '{{ nginx_site_firefish_front_domain }}'
    certbot_install_acme_cert_ca_bundle: '{{ nginx_site_firefish_front_ca_bundle_path }}'
    certbot_install_acme_cert_on_calendar: '{{ certbot_renew_on_calendar }}'
    certbot_install_hook_type: nginx

- name: Install site
  ansible.builtin.template:
    src: etc/nginx/sites-available/firefish_front.conf
    dest: /etc/nginx/sites-available/firefish_front.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/nginx-site-validate %s
  become: true
  notify:
    - Reload nginx

- name: Install maintenance site
  ansible.builtin.template:
    src: etc/nginx/sites-available/firefish_front_maintenance.conf
    dest: /etc/nginx/sites-available/firefish_front_maintenance.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: /opt/bin/nginx-site-validate %s
  become: true
  notify:
    - Reload nginx

- name: Install maintenance page
  ansible.builtin.template:
    src: var/www/html/firefish_front_maintenance.html
    dest: /var/www/html/firefish_front_maintenance.html
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/firefish_front.conf
    dest: /etc/nginx/sites-enabled/firefish_front.conf
    owner: root
    group: root
    state: link
  become: true
  when: not nginx_site_firefish_front_maintenance_mode
  notify:
    - Restart nginx

- name: Disable maintenance site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/firefish_front_maintenance.conf
    state: absent
  become: true
  when: not nginx_site_firefish_front_maintenance_mode
  notify:
    - Restart nginx

- name: Enable maintenance site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/firefish_front_maintenance.conf
    dest: /etc/nginx/sites-enabled/firefish_front_maintenance.conf
    owner: root
    group: root
    state: link
  become: true
  when: nginx_site_firefish_front_maintenance_mode
  notify:
    - Restart nginx

- name: Disable site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/firefish_front.conf
    state: absent
  become: true
  when: nginx_site_firefish_front_maintenance_mode
  notify:
    - Restart nginx
